# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.cos_queue_config_inner_id import CosQueueConfigInnerId
from openapi_client.models.cos_queue_config_inner_min_bw import CosQueueConfigInnerMinBw
from typing import Optional, Set
from typing_extensions import Self

class CosQueueConfigInner(BaseModel):
    """
    CosQueueConfigInner
    """ # noqa: E501
    id: Optional[CosQueueConfigInnerId] = None
    min_bw: Optional[CosQueueConfigInnerMinBw] = None
    mgmt_type: Optional[StrictStr] = Field(default=None, description="CoS Management Type")
    schedule_type: Optional[StrictStr] = Field(default=None, description="CoS Schedule Type")
    __properties: ClassVar[List[str]] = ["id", "min_bw", "mgmt_type", "schedule_type"]

    @field_validator('mgmt_type')
    def mgmt_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['TailDrop', 'Wred']):
            raise ValueError("must be one of enum values ('TailDrop', 'Wred')")
        return value

    @field_validator('schedule_type')
    def schedule_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Weighted', 'Strict']):
            raise ValueError("must be one of enum values ('Weighted', 'Strict')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CosQueueConfigInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of min_bw
        if self.min_bw:
            _dict['min_bw'] = self.min_bw.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CosQueueConfigInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": CosQueueConfigInnerId.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "min_bw": CosQueueConfigInnerMinBw.from_dict(obj["min_bw"]) if obj.get("min_bw") is not None else None,
            "mgmt_type": obj.get("mgmt_type"),
            "schedule_type": obj.get("schedule_type")
        })
        return _obj


