# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class Dot1dStpEntriesInner(BaseModel):
    """
    Dot1dStpEntriesInner
    """  # noqa: E501

    port: Optional[StrictInt] = Field(default=None, description="Port interface number")
    priority: Optional[StrictInt] = Field(
        default=None, description="Spanning Tree port priority"
    )
    state: Optional[StrictStr] = Field(
        default=None, description="Spanning Tree port state"
    )
    path_cost: Optional[StrictInt] = Field(
        default=None,
        description="Spanning Tree path cost for the port.",
        alias="pathCost",
    )
    designated_root: Optional[StrictStr] = Field(
        default=None,
        description="Spanning Tree designated root for the switch.",
        alias="designatedRoot",
    )
    designated_cost: Optional[StrictInt] = Field(
        default=None,
        description="Spanning Tree designated cost for the port",
        alias="designatedCost",
    )
    designated_bridge: Optional[StrictStr] = Field(
        default=None,
        description="Spanning Tree designated bridge for the port",
        alias="designatedBridge",
    )
    designated_port: Optional[StrictStr] = Field(
        default=None,
        description="Spanning Tree designated port ID",
        alias="designatedPort",
    )
    __properties: ClassVar[List[str]] = [
        "port",
        "priority",
        "state",
        "pathCost",
        "designatedRoot",
        "designatedCost",
        "designatedBridge",
        "designatedPort",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Dot1dStpEntriesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Dot1dStpEntriesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "port": obj.get("port"),
                "priority": obj.get("priority"),
                "state": obj.get("state"),
                "pathCost": obj.get("pathCost"),
                "designatedRoot": obj.get("designatedRoot"),
                "designatedCost": obj.get("designatedCost"),
                "designatedBridge": obj.get("designatedBridge"),
                "designatedPort": obj.get("designatedPort"),
            }
        )
        return _obj
