# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class DualImageStatus(BaseModel):
    """
    DualImageStatus
    """  # noqa: E501

    image1_label: Optional[StrictStr] = Field(
        default="image1", description="image1 label", alias="image1Label"
    )
    image1_descr: Optional[StrictStr] = Field(
        default=None, description="image1 description", alias="image1Descr"
    )
    image1_version: Optional[StrictStr] = Field(
        default=None, description="image1 version", alias="image1Version"
    )
    image2_label: Optional[StrictStr] = Field(
        default="image2", description="image2 label", alias="image2Label"
    )
    image2_descr: Optional[StrictStr] = Field(
        default=None, description="image2 description", alias="image2Descr"
    )
    image2_version: Optional[StrictStr] = Field(
        default=None, description="image2 version", alias="image2Version"
    )
    activated_img_label: Optional[StrictStr] = Field(
        default=None, description="active image label", alias="activatedImgLabel"
    )
    __properties: ClassVar[List[str]] = [
        "image1Label",
        "image1Descr",
        "image1Version",
        "image2Label",
        "image2Descr",
        "image2Version",
        "activatedImgLabel",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DualImageStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DualImageStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "image1Label": (
                    obj.get("image1Label")
                    if obj.get("image1Label") is not None
                    else "image1"
                ),
                "image1Descr": obj.get("image1Descr"),
                "image1Version": obj.get("image1Version"),
                "image2Label": (
                    obj.get("image2Label")
                    if obj.get("image2Label") is not None
                    else "image2"
                ),
                "image2Descr": obj.get("image2Descr"),
                "image2Version": obj.get("image2Version"),
                "activatedImgLabel": obj.get("activatedImgLabel"),
            }
        )
        return _obj
