# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.lldp_remote_devices_mgmt_addresses_inner import (
    LldpRemoteDevicesMgmtAddressesInner,
)
from typing import Optional, Set
from typing_extensions import Self


class LldpRemoteDevices(BaseModel):
    """
    LldpRemoteDevices
    """  # noqa: E501

    id: Optional[StrictInt] = Field(default=None, description="LLDP ID Number")
    if_index: Optional[StrictInt] = Field(
        default=None, description="Internal interface number", alias="ifIndex"
    )
    remote_id: Optional[StrictInt] = Field(
        default=None,
        description="Identifier for device on remote system",
        alias="remoteId",
    )
    chassis_id: Optional[StrictStr] = Field(
        default=None, description="Remote device hardware platform", alias="chassisId"
    )
    chassis_id_subtype: Optional[StrictInt] = Field(
        default=None,
        description="Chassis ID field subtype:   * `1` = Chassis component   * `2` = Interface alias   * `3` = Port component   * `4` = MAC address   * `5` = Network address   * `6` = Interface name   * `7` = Local ",
        alias="chassisIdSubtype",
    )
    remote_port_id: Optional[StrictStr] = Field(
        default=None,
        description="Device port that transmitted LLDP data",
        alias="remotePortId",
    )
    remote_port_id_subtype: Optional[StrictInt] = Field(
        default=None,
        description="Remote port field subtype:   * `1` = Chassis component   * `2` = Interface alias   * `3` = Port component   * `4` = MAC address   * `5` = Network address   * `6` = Interface name   * `7` = Local ",
        alias="remotePortIdSubtype",
    )
    remote_port_desc: Optional[StrictStr] = Field(
        default=None,
        description="Remote system port description",
        alias="remotePortDesc",
    )
    remote_sys_name: Optional[StrictStr] = Field(
        default=None,
        description="Name assigned to the device in the remote system",
        alias="remoteSysName",
    )
    remote_sys_desc: Optional[StrictStr] = Field(
        default=None,
        description="Description assigned to the device in the remote system",
        alias="remoteSysDesc",
    )
    sys_capabilities_supported: Optional[StrictStr] = Field(
        default=None,
        description="List of primary functions supported by the remote system",
        alias="sysCapabilitiesSupported",
    )
    sys_capabilities_enabled: Optional[StrictStr] = Field(
        default=None,
        description="List of primary functions enabled on the remote system",
        alias="sysCapabilitiesEnabled",
    )
    mgmt_addresses: Optional[List[LldpRemoteDevicesMgmtAddressesInner]] = Field(
        default=None, alias="mgmtAddresses"
    )
    remote_ttl: Optional[StrictInt] = Field(
        default=None,
        description="Remote device Time To Live information offset",
        alias="remoteTTL",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "ifIndex",
        "remoteId",
        "chassisId",
        "chassisIdSubtype",
        "remotePortId",
        "remotePortIdSubtype",
        "remotePortDesc",
        "remoteSysName",
        "remoteSysDesc",
        "sysCapabilitiesSupported",
        "sysCapabilitiesEnabled",
        "mgmtAddresses",
        "remoteTTL",
    ]

    @field_validator("chassis_id_subtype")
    def chassis_id_subtype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 5, 6, 7]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 5, 6, 7)")
        return value

    @field_validator("remote_port_id_subtype")
    def remote_port_id_subtype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 5, 6, 7]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 5, 6, 7)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LldpRemoteDevices from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mgmt_addresses (list)
        _items = []
        if self.mgmt_addresses:
            for _item_mgmt_addresses in self.mgmt_addresses:
                if _item_mgmt_addresses:
                    _items.append(_item_mgmt_addresses.to_dict())
            _dict["mgmtAddresses"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LldpRemoteDevices from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "ifIndex": obj.get("ifIndex"),
                "remoteId": obj.get("remoteId"),
                "chassisId": obj.get("chassisId"),
                "chassisIdSubtype": obj.get("chassisIdSubtype"),
                "remotePortId": obj.get("remotePortId"),
                "remotePortIdSubtype": obj.get("remotePortIdSubtype"),
                "remotePortDesc": obj.get("remotePortDesc"),
                "remoteSysName": obj.get("remoteSysName"),
                "remoteSysDesc": obj.get("remoteSysDesc"),
                "sysCapabilitiesSupported": obj.get("sysCapabilitiesSupported"),
                "sysCapabilitiesEnabled": obj.get("sysCapabilitiesEnabled"),
                "mgmtAddresses": (
                    [
                        LldpRemoteDevicesMgmtAddressesInner.from_dict(_item)
                        for _item in obj["mgmtAddresses"]
                    ]
                    if obj.get("mgmtAddresses") is not None
                    else None
                ),
                "remoteTTL": obj.get("remoteTTL"),
            }
        )
        return _obj
