# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PoeConfigGet(BaseModel):
    """
    PoeConfigGet
    """ # noqa: E501
    firmware_version: Optional[StrictStr] = Field(default=None, description="PoE Firmware Version", alias="firmwareVersion")
    pse_main_operation_status: Optional[StrictStr] = Field(default=None, description="Power Sourcing Equipment main operation status", alias="pseMainOperationStatus")
    total_power_consumed_watts: Optional[StrictStr] = Field(default=None, description="Total power consumed in watts", alias="totalPowerConsumedWatts")
    power_managment_mode: Optional[StrictStr] = Field(default=None, description="PoE power management mode", alias="powerManagmentMode")
    traps: Optional[StrictStr] = None
    power_detection_mode: Optional[StrictInt] = Field(default=None, description="PoE Detection Mode:  * `0` = Invalid  * `1` = Legacy  * `2` = 4pt 802.3af  * `3` = 4pt 802.3af and legacy  * `4` = 2pt 802.3af  * `5` = 2pt 802.3af and legacy  * `6` = None  * `7` = Count ", alias="powerDetectionMode")
    __properties: ClassVar[List[str]] = ["firmwareVersion", "pseMainOperationStatus", "totalPowerConsumedWatts", "powerManagmentMode", "traps", "powerDetectionMode"]

    @field_validator('pse_main_operation_status')
    def pse_main_operation_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true', 'false']):
            raise ValueError("must be one of enum values ('true', 'false')")
        return value

    @field_validator('power_managment_mode')
    def power_managment_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['dynamic', 'static']):
            raise ValueError("must be one of enum values ('dynamic', 'static')")
        return value

    @field_validator('traps')
    def traps_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enable', 'disable']):
            raise ValueError("must be one of enum values ('enable', 'disable')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PoeConfigGet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PoeConfigGet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "firmwareVersion": obj.get("firmwareVersion"),
            "pseMainOperationStatus": obj.get("pseMainOperationStatus"),
            "totalPowerConsumedWatts": obj.get("totalPowerConsumedWatts"),
            "powerManagmentMode": obj.get("powerManagmentMode"),
            "traps": obj.get("traps"),
            "powerDetectionMode": obj.get("powerDetectionMode")
        })
        return _obj


