# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SnoopingVlanInner(BaseModel):
    """
    SnoopingVlanInner
    """ # noqa: E501
    vlan_id: Optional[StrictInt] = Field(default=None, description="VLAN ID", alias="vlanId")
    family: Optional[StrictStr] = Field(default=None, description="Snooping family")
    fast_leave_mode: Optional[StrictStr] = Field(default=None, description="Snooping fast leave mode for the specified VLAN", alias="fastLeaveMode")
    vlan_mode: Optional[StrictStr] = Field(default=None, description="Snooping mode for the specified VLAN", alias="vlanMode")
    report_supp_mode: Optional[StrictStr] = Field(default=None, description="Snooping report suppression mode for the specified VLAN", alias="reportSuppMode")
    proxy_querier_mode: Optional[StrictStr] = Field(default=None, description="Proxy Querier Admin mode for the specified VLAN.", alias="proxyQuerierMode")
    group_membership_interval: Optional[StrictInt] = Field(default=None, description="IGMP/MLD snooping group membership interval for the specified VLAN.", alias="groupMembershipInterval")
    max_response_time: Optional[StrictInt] = Field(default=None, description="IGMP/MLD snooping maximum response time for the specified VLAN.", alias="maxResponseTime")
    __properties: ClassVar[List[str]] = ["vlanId", "family", "fastLeaveMode", "vlanMode", "reportSuppMode", "proxyQuerierMode", "groupMembershipInterval", "maxResponseTime"]

    @field_validator('family')
    def family_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['mld', 'igmp']):
            raise ValueError("must be one of enum values ('mld', 'igmp')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnoopingVlanInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnoopingVlanInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vlanId": obj.get("vlanId"),
            "family": obj.get("family"),
            "fastLeaveMode": obj.get("fastLeaveMode"),
            "vlanMode": obj.get("vlanMode"),
            "reportSuppMode": obj.get("reportSuppMode"),
            "proxyQuerierMode": obj.get("proxyQuerierMode"),
            "groupMembershipInterval": obj.get("groupMembershipInterval"),
            "maxResponseTime": obj.get("maxResponseTime")
        })
        return _obj


