# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SwLagCfg(BaseModel):
    """
    SwLagCfg
    """ # noqa: E501
    lag_group: Optional[Annotated[int, Field(le=128, strict=True, ge=0)]] = Field(default=None, description="LAG Group:   * `0` = Create a new LAG group   * Non-zero values will modify an existing LAB group. ")
    name: StrictStr = Field(description="LAG description")
    group_id: StrictInt = Field(description="LAG Group ID", alias="groupId")
    admin_mode: StrictBool = Field(description="LAG enabled state", alias="adminMode")
    type: StrictInt = Field(description="LAG Type:   * `0` = Dynamic or Static LAG   * `1` = Static LAG ")
    members: List[StrictInt] = Field(description="LAG Port members")
    __properties: ClassVar[List[str]] = ["lag_group", "name", "groupId", "adminMode", "type", "members"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwLagCfg from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwLagCfg from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lag_group": obj.get("lag_group"),
            "name": obj.get("name"),
            "groupId": obj.get("groupId"),
            "adminMode": obj.get("adminMode"),
            "type": obj.get("type"),
            "members": obj.get("members")
        })
        return _obj


