# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SwPortstatsNeighborInfo(BaseModel):
    """
    Neighbor connected device Information
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Neighbor name")
    description: Optional[StrictStr] = Field(default=None, description="Neighbor description")
    capabilities: Optional[StrictStr] = Field(default=None, description="Neighbor capabilites")
    chassis_id: Optional[StrictStr] = Field(default=None, description="Neighbor chassis ID", alias="chassisId")
    chassis_id_subtype: Optional[StrictInt] = Field(default=None, description="Neighbor chassis subtype:   * `1` = SUBTYPE_CHASSIS_COMP   * `2` = SUBTYPE_INTF_ALIAS   * `3` = SUBTYPE_PORT_COMP   * `4` = SUBTYPE_MAC_ADDR   * `5` = SUBTYPE_NET_ADDR   * `6` = SUBTYPE_INTF_NAME   * `7` = SUBTYPE_LOCAL ", alias="chassisIdSubtype")
    port_id: Optional[StrictStr] = Field(default=None, description="Neighbor port ID", alias="portId")
    port_id_subtype: Optional[StrictInt] = Field(default=None, description="Neighbor port subtype:   * `1` = SUBTYPE_INTF_ALIAS   * `2` = SUBTYPE_PORT_COMP   * `3` = SUBTYPE_MAC_ADDR   * `4` = SUBTYPE_NET_ADDR   * `5` = SUBTYPE_INTF_NAME   * `6` = SUBTYPE_AGENT_ID   * `7` = SUBTYPE_LOCAL ", alias="portIdSubtype")
    port_description: Optional[StrictStr] = Field(default=None, description="Neighbor port description", alias="portDescription")
    mgmt_ip_address: Optional[StrictStr] = Field(default=None, description="Neighbor management IP Address", alias="mgmtIpAddress")
    __properties: ClassVar[List[str]] = ["name", "description", "capabilities", "chassisId", "chassisIdSubtype", "portId", "portIdSubtype", "portDescription", "mgmtIpAddress"]

    @field_validator('chassis_id_subtype')
    def chassis_id_subtype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 5, 6, 7]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 5, 6, 7)")
        return value

    @field_validator('port_id_subtype')
    def port_id_subtype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 5, 6, 7]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 5, 6, 7)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwPortstatsNeighborInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwPortstatsNeighborInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "capabilities": obj.get("capabilities"),
            "chassisId": obj.get("chassisId"),
            "chassisIdSubtype": obj.get("chassisIdSubtype"),
            "portId": obj.get("portId"),
            "portIdSubtype": obj.get("portIdSubtype"),
            "portDescription": obj.get("portDescription"),
            "mgmtIpAddress": obj.get("mgmtIpAddress")
        })
        return _obj


