# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.swcfg_vlan_igmp_config import SwcfgVlanIgmpConfig
from typing import Optional, Set
from typing_extensions import Self


class SwcfgVlan(BaseModel):
    """
    SwcfgVlan
    """  # noqa: E501

    vlan_id: Annotated[int, Field(le=4096, strict=True, ge=1)] = Field(
        description="VLAN ID", alias="vlanId"
    )
    name: StrictStr = Field(description="VLAN Name")
    voice_vlan_state: Optional[StrictBool] = Field(
        default=False, description="Voice VLAN status", alias="voiceVlanState"
    )
    auto_voip_state: Optional[StrictBool] = Field(
        default=False, description="AutoVoIP", alias="autoVoipState"
    )
    auto_video_state: Optional[StrictBool] = Field(
        default=False, description="Auto Video", alias="autoVideoState"
    )
    igmp_config: Optional[SwcfgVlanIgmpConfig] = Field(default=None, alias="igmpConfig")
    __properties: ClassVar[List[str]] = [
        "vlanId",
        "name",
        "voiceVlanState",
        "autoVoipState",
        "autoVideoState",
        "igmpConfig",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwcfgVlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of igmp_config
        if self.igmp_config:
            _dict["igmpConfig"] = self.igmp_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwcfgVlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "vlanId": obj.get("vlanId"),
                "name": obj.get("name"),
                "voiceVlanState": (
                    obj.get("voiceVlanState")
                    if obj.get("voiceVlanState") is not None
                    else False
                ),
                "autoVoipState": (
                    obj.get("autoVoipState")
                    if obj.get("autoVoipState") is not None
                    else False
                ),
                "autoVideoState": (
                    obj.get("autoVideoState")
                    if obj.get("autoVideoState") is not None
                    else False
                ),
                "igmpConfig": (
                    SwcfgVlanIgmpConfig.from_dict(obj["igmpConfig"])
                    if obj.get("igmpConfig") is not None
                    else None
                ),
            }
        )
        return _obj
