# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.swcfg_port_rtlimit_bcast import SwcfgPortRtlimitBcast
from openapi_client.models.swcfg_port_rtlimit_mcast import SwcfgPortRtlimitMcast
from openapi_client.models.swcfg_port_rtlimit_ucast import SwcfgPortRtlimitUcast
from typing import Optional, Set
from typing_extensions import Self


class SwcfgPort(BaseModel):
    """
    SwcfgPort
    """  # noqa: E501

    id: StrictInt = Field(description="Port Number", alias="ID")
    description: StrictStr = Field(description="Port description label")
    port_type: StrictInt = Field(
        description="Port configuration type:   * `0` = MODE_NONE   * `1` = MODE_GENERAL   * `2` = MODE_ACCESS   * `3` = MODE_TRUNK   * `4` = MODE_PRIVATE_HOST   * `5` = MODE_PRIVATE_PROMISC ",
        alias="portType",
    )
    admin_mode: StrictBool = Field(
        description="Enable physical port interface", alias="adminMode"
    )
    port_speed: Optional[StrictInt] = Field(
        default=0,
        description="Port link speed:   * `0` = auto   * `1` = SP10   * `2` = SP100   * `3` = SP1000   * `4` = SP10G ",
        alias="portSpeed",
    )
    duplex_mode: Optional[StrictInt] = Field(
        default=2,
        description="Duplex Mode:   * `2` = auto   * `1` = full   * `0` = half ",
        alias="duplexMode",
    )
    link_status: Optional[StrictInt] = Field(
        default=1,
        description="Link up or down Status (read-only):   * `0` = Up   * `1` = Down ",
        alias="linkStatus",
    )
    link_trap: Optional[StrictBool] = Field(
        default=True, description="Enable link trap", alias="linkTrap"
    )
    max_frame_size: Optional[Annotated[int, Field(le=9198, strict=True, ge=1500)]] = (
        Field(default=1518, description="Max frame size", alias="maxFrameSize")
    )
    is_po_e: StrictBool = Field(description="Port is PoE capable", alias="isPoE")
    tx_rate: Annotated[int, Field(le=100, strict=True, ge=0)] = Field(
        description="Traffic shaping rate for the interface as a percentage. 0% means traffic is Unlimited. 100% means traffic is Blocked/Limited.",
        alias="txRate",
    )
    rtlimit_ucast: SwcfgPortRtlimitUcast = Field(alias="rtlimitUcast")
    rtlimit_mcast: SwcfgPortRtlimitMcast = Field(alias="rtlimitMcast")
    rtlimit_bcast: SwcfgPortRtlimitBcast = Field(alias="rtlimitBcast")
    port_vlan_id: Annotated[int, Field(le=4096, strict=True, ge=1)] = Field(
        description="Port's VLAN ID", alias="portVlanId"
    )
    def_vlan_prio: Annotated[int, Field(le=7, strict=True, ge=0)] = Field(
        description="Default VLAN priority", alias="defVlanPrio"
    )
    schedule_name: Optional[StrictStr] = Field(
        default=None, description="Name of the schedule", alias="scheduleName"
    )
    __properties: ClassVar[List[str]] = [
        "ID",
        "description",
        "portType",
        "adminMode",
        "portSpeed",
        "duplexMode",
        "linkStatus",
        "linkTrap",
        "maxFrameSize",
        "isPoE",
        "txRate",
        "rtlimitUcast",
        "rtlimitMcast",
        "rtlimitBcast",
        "portVlanId",
        "defVlanPrio",
        "scheduleName",
    ]

    @field_validator("port_type")
    def port_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([0, 1, 2, 3, 4, 5]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4, 5)")
        return value

    @field_validator("port_speed")
    def port_speed_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2, 3, 4]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4)")
        return value

    @field_validator("duplex_mode")
    def duplex_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([2, 1, 0]):
            raise ValueError("must be one of enum values (2, 1, 0)")
        return value

    @field_validator("link_status")
    def link_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwcfgPort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rtlimit_ucast
        if self.rtlimit_ucast:
            _dict["rtlimitUcast"] = self.rtlimit_ucast.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rtlimit_mcast
        if self.rtlimit_mcast:
            _dict["rtlimitMcast"] = self.rtlimit_mcast.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rtlimit_bcast
        if self.rtlimit_bcast:
            _dict["rtlimitBcast"] = self.rtlimit_bcast.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwcfgPort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "ID": obj.get("ID"),
                "description": obj.get("description"),
                "portType": (
                    obj.get("portType") if obj.get("portType") is not None else 1
                ),
                "adminMode": (
                    obj.get("adminMode") if obj.get("adminMode") is not None else True
                ),
                "portSpeed": (
                    obj.get("portSpeed") if obj.get("portSpeed") is not None else 0
                ),
                "duplexMode": (
                    obj.get("duplexMode") if obj.get("duplexMode") is not None else 2
                ),
                "linkStatus": (
                    obj.get("linkStatus") if obj.get("linkStatus") is not None else 1
                ),
                "linkTrap": (
                    obj.get("linkTrap") if obj.get("linkTrap") is not None else True
                ),
                "maxFrameSize": (
                    obj.get("maxFrameSize")
                    if obj.get("maxFrameSize") is not None
                    else 1518
                ),
                "isPoE": obj.get("isPoE") if obj.get("isPoE") is not None else True,
                "txRate": obj.get("txRate") if obj.get("txRate") is not None else 0,
                "rtlimitUcast": (
                    SwcfgPortRtlimitUcast.from_dict(obj["rtlimitUcast"])
                    if obj.get("rtlimitUcast") is not None
                    else None
                ),
                "rtlimitMcast": (
                    SwcfgPortRtlimitMcast.from_dict(obj["rtlimitMcast"])
                    if obj.get("rtlimitMcast") is not None
                    else None
                ),
                "rtlimitBcast": (
                    SwcfgPortRtlimitBcast.from_dict(obj["rtlimitBcast"])
                    if obj.get("rtlimitBcast") is not None
                    else None
                ),
                "portVlanId": (
                    obj.get("portVlanId") if obj.get("portVlanId") is not None else 1
                ),
                "defVlanPrio": (
                    obj.get("defVlanPrio") if obj.get("defVlanPrio") is not None else 0
                ),
                "scheduleName": obj.get("scheduleName"),
            }
        )
        return _obj
