# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class SystemConfigGet(BaseModel):
    """
    SystemConfigGet
    """  # noqa: E501

    sys_access_line: Optional[StrictStr] = Field(
        default=None, description="System access type setting", alias="sysAccessLine"
    )
    sys_line_terminal_len: Optional[StrictInt] = Field(
        default=None,
        description="Terminal length of an access line.",
        alias="sysLineTerminalLen",
    )
    sys_serial_time_out: Optional[StrictInt] = Field(
        default=None, description="Serial timeout.", alias="sysSerialTimeOut"
    )
    sys_telnet_server_admin_mode: Optional[StrictStr] = Field(
        default=None,
        description="Telnet server admin mode.",
        alias="sysTelnetServerAdminMode",
    )
    __properties: ClassVar[List[str]] = [
        "sysAccessLine",
        "sysLineTerminalLen",
        "sysSerialTimeOut",
        "sysTelnetServerAdminMode",
    ]

    @field_validator("sys_access_line")
    def sys_access_line_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["console", "telnet", "ssh"]):
            raise ValueError("must be one of enum values ('console', 'telnet', 'ssh')")
        return value

    @field_validator("sys_telnet_server_admin_mode")
    def sys_telnet_server_admin_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["enabled", "disabled"]):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemConfigGet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemConfigGet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "sysAccessLine": obj.get("sysAccessLine"),
                "sysLineTerminalLen": obj.get("sysLineTerminalLen"),
                "sysSerialTimeOut": obj.get("sysSerialTimeOut"),
                "sysTelnetServerAdminMode": obj.get("sysTelnetServerAdminMode"),
            }
        )
        return _obj
