# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class VlanIp(BaseModel):
    """
    VlanIp
    """  # noqa: E501

    vlan_id: Optional[StrictInt] = Field(
        default=None, description="VLAN ID", alias="vlanId"
    )
    dhcp_status: Optional[StrictBool] = Field(
        default=None, description="Enable VLAN DHCP client", alias="dhcpStatus"
    )
    ip_addr: Optional[StrictStr] = Field(
        default=None, description="VLAN IP address", alias="ipAddr"
    )
    ip_mask: Optional[StrictStr] = Field(
        default=None, description="VLAN subnet mask", alias="ipMask"
    )
    ip_mtu: Optional[StrictInt] = Field(
        default=None,
        description="VLAN Maximum Transmission Unit (MTU) size",
        alias="ipMtu",
    )
    vlan_routing: Optional[StrictBool] = Field(
        default=None, description="Enable VLAN routing", alias="vlanRouting"
    )
    __properties: ClassVar[List[str]] = [
        "vlanId",
        "dhcpStatus",
        "ipAddr",
        "ipMask",
        "ipMtu",
        "vlanRouting",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VlanIp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VlanIp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "vlanId": obj.get("vlanId"),
                "dhcpStatus": obj.get("dhcpStatus"),
                "ipAddr": obj.get("ipAddr"),
                "ipMask": obj.get("ipMask"),
                "ipMtu": obj.get("ipMtu"),
                "vlanRouting": obj.get("vlanRouting"),
            }
        )
        return _obj
