# Generated by Django 5.1.3 on 2024-11-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
