services:
  syslog:
    image: balabit/syslog-ng:latest
    container_name: netctrl_syslog
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    volumes:
      - syslog_data:/var/log
      - ./syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
    networks:
      - netctrl_network
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYSLOG
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  # MongoDB: Required for Graylog
  mongodb:
    image: mongo:4.2
    container_name: netctrl_mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - netctrl_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Elasticsearch: Required for Graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: netctrl_elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - netctrl_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Graylog: Web-based log viewer and management
  logviewer:
    image: graylog/graylog:4.3
    container_name: netctrl_logviewer
    ports:
      - "12201:12201/udp"  # GELF UDP
      - "8080:9000"        # Web interface
    volumes:
      - graylog_data:/usr/share/graylog/data
      - syslog_data:/var/log:ro
    environment:
      - GRAYLOG_PASSWORD_SECRET=N3tCtrl_Gr@yL0g_S3cret
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # admin
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:8080/logs/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    networks:
      - netctrl_network
    depends_on:
      - mongodb
      - elasticsearch
      - syslog
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  postgres:
    image: postgres:14
    container_name: netctrl_postgres
    environment:
      POSTGRES_DB: netctrl_db
      POSTGRES_USER: netctrl_user
      POSTGRES_PASSWORD: N3tCtrl_P@ssw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netctrl_network
    depends_on:
      - syslog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  nginx:
    image: nginx:1.21
    container_name: netctrl_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - static_volume:/srv/NetCtrl/static
      - media_volume:/srv/NetCtrl/media
    networks:
      - netctrl_network
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: netctrl_app
    environment:
      - DJANGO_SETTINGS_MODULE=netctrl.settings
      - POSTGRES_DB=netctrl_db
      - POSTGRES_USER=netctrl_user
      - POSTGRES_PASSWORD=N3tCtrl_P@ssw0rd
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - SYSLOG_HOST=syslog
      - SYSLOG_PORT=601
    volumes:
      - static_volume:/srv/NetCtrl/static
      - media_volume:/srv/NetCtrl/media
    networks:
      - netctrl_network
    depends_on:
      - postgres
      - syslog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  syslog_data:
  postgres_data:
  static_volume:
  media_volume:
  mongodb_data:
  elasticsearch_data:
  graylog_data:

networks:
  netctrl_network:
    driver: bridge
