services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: netctrl.settings.base

      SECRET_KEY: ${SECRET_KEY:-default_secret_key}
      DEBUG: "${DEBUG:-false}"  # Default to false if not provided
      DB_ENGINE: ${DB_ENGINE:-django.db.backends.postgresql}
      DB_NAME: ${DB_NAME:-default_db}
      DB_USER: ${DB_USER:-default_user}
      DB_PASSWORD: ${DB_PASSWORD:-default_password}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-127.0.0.1,localhost}
      SWITCH_USERNAME: ${SWITCH_USERNAME:-admin}
      SWITCH_PASSWORD: ${SWITCH_PASSWORD:-password}
      SWITCH_IP: ${SWITCH_IP:-192.168.99.92}
      USE_HTTPS: ${USE_HTTPS:-true}
      REDIS_HOST: redis  # Redis hostname
      REDIS_PORT: 6379   # Redis port
    depends_on:
      - db
      - redis
    container_name: web
    hostname: web

  db:
    image: postgres:15
    container_name: db
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER:-default_user}"  # Default to 'default_user'
      POSTGRES_PASSWORD: "${DB_PASSWORD:-default_password}"  # Default to 'default_password'
      POSTGRES_DB: "${DB_NAME:-default_db}"  # Default to 'default_db'

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    sysctls:
      - net.core.somaxconn=1024

volumes:
  postgres_data: