[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts =
    --cov=.
    --cov-report=html
    --cov-report=term-missing
    --cov-fail-under=80
    --no-migrations
markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    slow: Tests that are expected to be slow
    api: API tests
    asyncio: mark test as async test
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
asyncio_mode = auto
