# Generated by Django 5.1.5 on 2025-01-31 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the action occurred",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("api", "API Access"),
                            ("other", "Other"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the action",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "object_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the target object",
                        null=True,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of the changes made",
                        null=True,
                        verbose_name="Changes",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the action",
                        null=True,
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of the target object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_auditl_timesta_189a84_idx"
                    ),
                    models.Index(
                        fields=["user"], name="core_auditl_user_id_2ff9b7_idx"
                    ),
                    models.Index(
                        fields=["action"], name="core_auditl_action_d9fb24_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_auditl_content_fec0c4_idx",
                    ),
                ],
            },
        ),
    ]
