# Generated by Django 4.2.10 on 2025-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique switch identifier (e.g. PDX-RIG-12-SW01)', max_length=100, unique=True)),
                ('in_band_ip', models.GenericIPAddressField(help_text='Private IP for management plane access', verbose_name='In-band IP')),
                ('out_band_ip', models.GenericIPAddressField(help_text='Private IP for data plane access', verbose_name='Out-of-band IP')),
                ('username', models.CharField(help_text='Privileged account for CLI access', max_length=100)),
                ('encrypted_password', models.BinaryField(help_text='Fernet-encrypted credentials')),
                ('cert_expiry', models.DateField(blank=True, help_text='Next certificate rotation date', null=True)),
                ('last_cert_renewal', models.DateTimeField(blank=True, help_text='Timestamp of last successful cert renewal', null=True)),
                ('cli_timeout', models.PositiveSmallIntegerField(default=30, help_text='SSH session timeout in seconds (per M4300 docs)')),
                ('aaa_config', models.TextField(help_text='AAA authorization config in CLI format', max_length=1024)),
                ('igmp_snooping_enabled', models.BooleanField(default=True, help_text='Enable IGMP snooping per port security specs')),
            ],
            options={
                'verbose_name_plural': 'Switches',
            },
        ),
    ]
