"""
Django settings for netctrl project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', "django-insecure-3^r@-ojml9!&-esnjq6+@e0$ne71i(8cok$rml7o#ixki*!+#k")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    "chunked_upload",
    "whitenoise.runserver_nostatic",
    
    # Local apps
    "cms.apps.CmsConfig",
    "network.apps.NetworkConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "netctrl.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "netctrl.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use SQLite for development by default
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Use PostgreSQL if explicitly configured
if os.environ.get('USE_POSTGRES', 'False') == 'True':
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get('POSTGRES_DB', 'netctrl_db'),
            "USER": os.environ.get('POSTGRES_USER', 'netctrl_user'),
            "PASSWORD": os.environ.get('POSTGRES_PASSWORD', 'netctrl_password'),
            "HOST": os.environ.get('POSTGRES_HOST', 'postgres'),
            "PORT": os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/cms/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Chunked Upload settings
CHUNKED_UPLOAD_PATH = 'uploads/chunks/'
CHUNKED_UPLOAD_MAX_BYTES = 5 * 1024 * 1024 * 1024  # 5GB
CHUNKED_UPLOAD_STORAGE_CLASS = 'django.core.files.storage.FileSystemStorage'
CHUNKED_UPLOAD_ABSTRACT_MODEL = False
CHUNKED_UPLOAD_COMPLETE_EXT = '.done'

# Logging - Integrate with our custom TCPSysLogHandler
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'syslog': {
            'level': 'INFO',
            'class': 'netctrl.logging_config.TCPSysLogHandler',
            'formatter': 'verbose',
            'facility': 'local1',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'syslog'],
            'level': 'INFO',
            'propagate': True,
        },
        'cms': {
            'handlers': ['console', 'syslog'],
            'level': 'INFO',
            'propagate': True,
        },
        'network': {
            'handlers': ['console', 'syslog'],
            'level': 'INFO',
            'propagate': True,
        },
        'netctrl': {
            'handlers': ['console', 'syslog'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Try to import our custom logging configuration
try:
    from netctrl.logging_config import TCPSysLogHandler
except ImportError:
    # Fall back to standard logging if custom handler is not available
    for logger_name, logger_config in LOGGING['loggers'].items():
        if 'syslog' in logger_config['handlers']:
            logger_config['handlers'].remove('syslog')
    
    # Add a warning about missing the custom handler
    import warnings
    warnings.warn("Custom TCPSysLogHandler not found. Falling back to console logging only.")

# GitHub Issue Reporter Configuration
APP_VERSION = '1.0.0'  # Update with your actual application version
GITHUB_TOKEN = "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"
GITHUB_REPOSITORY = "ready-1/NetCtrl"
