# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.device_info_temperature_sensors_inner import DeviceInfoTemperatureSensorsInner
from typing import Optional, Set
from typing_extensions import Self

class DeviceInfo(BaseModel):
    """
    DeviceInfo
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Switch display name")
    serial_number: Optional[StrictStr] = Field(default=None, description="Switch Serial Number", alias="serialNumber")
    mac_addr: Optional[StrictStr] = Field(default=None, description="Switch MAC Address", alias="macAddr")
    model: Optional[StrictStr] = Field(default=None, description="Switch Model Number")
    lan_ip_address: Optional[StrictStr] = Field(default=None, description="LAN IP Address", alias="lanIpAddress")
    sw_ver: Optional[StrictStr] = Field(default=None, description="Active firmware version", alias="swVer")
    last_reboot: Optional[StrictStr] = Field(default=None, description="Time of last reboot with time zone information", alias="lastReboot")
    num_of_ports: Optional[StrictInt] = Field(default=None, description="Total number of switch ports available", alias="numOfPorts")
    num_of_active_ports: Optional[StrictInt] = Field(default=None, description="Total number of currently active switch ports", alias="numOfActivePorts")
    rstp_state: Optional[StrictBool] = Field(default=None, description="RSTP State", alias="rstpState")
    memory_used: Optional[StrictStr] = Field(default=None, description="Amount of RAM used in KBs", alias="memoryUsed")
    memory_usage: Optional[StrictStr] = Field(default=None, description="% of memory usage", alias="memoryUsage")
    cpu_usage: Optional[StrictStr] = Field(default=None, description="% of CPU usage", alias="cpuUsage")
    fan_state: Optional[StrictStr] = Field(default=None, description="Fan status", alias="fanState")
    poe_state: Optional[StrictBool] = Field(default=None, description="PoE enabled status", alias="poeState")
    up_time: Optional[StrictStr] = Field(default=None, description="Up time of device", alias="upTime")
    temperature_sensors: Optional[List[DeviceInfoTemperatureSensorsInner]] = Field(default=None, alias="temperatureSensors")
    boot_version: Optional[StrictStr] = Field(default=None, description="Bootcode version of the Switch.", alias="bootVersion")
    rx_data: Optional[StrictInt] = Field(default=None, description="Total number of bytes received", alias="rxData")
    tx_data: Optional[StrictInt] = Field(default=None, description="Total number of bytes transmitted", alias="txData")
    admin_poe_power: Optional[StrictInt] = Field(default=None, description="Admin PoE power as selected from Web UI (unit is mW)", alias="adminPoePower")
    __properties: ClassVar[List[str]] = ["name", "serialNumber", "macAddr", "model", "lanIpAddress", "swVer", "lastReboot", "numOfPorts", "numOfActivePorts", "rstpState", "memoryUsed", "memoryUsage", "cpuUsage", "fanState", "poeState", "upTime", "temperatureSensors", "bootVersion", "rxData", "txData", "adminPoePower"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeviceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in temperature_sensors (list)
        _items = []
        if self.temperature_sensors:
            for _item_temperature_sensors in self.temperature_sensors:
                if _item_temperature_sensors:
                    _items.append(_item_temperature_sensors.to_dict())
            _dict['temperatureSensors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeviceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "serialNumber": obj.get("serialNumber"),
            "macAddr": obj.get("macAddr"),
            "model": obj.get("model"),
            "lanIpAddress": obj.get("lanIpAddress"),
            "swVer": obj.get("swVer"),
            "lastReboot": obj.get("lastReboot"),
            "numOfPorts": obj.get("numOfPorts"),
            "numOfActivePorts": obj.get("numOfActivePorts"),
            "rstpState": obj.get("rstpState"),
            "memoryUsed": obj.get("memoryUsed"),
            "memoryUsage": obj.get("memoryUsage"),
            "cpuUsage": obj.get("cpuUsage"),
            "fanState": obj.get("fanState"),
            "poeState": obj.get("poeState"),
            "upTime": obj.get("upTime"),
            "temperatureSensors": [DeviceInfoTemperatureSensorsInner.from_dict(_item) for _item in obj["temperatureSensors"]] if obj.get("temperatureSensors") is not None else None,
            "bootVersion": obj.get("bootVersion"),
            "rxData": obj.get("rxData"),
            "txData": obj.get("txData"),
            "adminPoePower": obj.get("adminPoePower")
        })
        return _obj


