# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Dot1dStpConfig(BaseModel):
    """
    Dot1dStpConfig
    """ # noqa: E501
    protocol_specification: Optional[StrictStr] = Field(default=None, description="STP protocol", alias="protocolSpecification")
    priority: Optional[Annotated[int, Field(le=61440, strict=True, ge=0)]] = Field(default=None, description="Bridge priority and displayed in multiples of 4096")
    time_since_topology_change: Optional[StrictInt] = Field(default=None, description="Time passed since topology change (seconds)", alias="timeSinceTopologyChange")
    top_changes: Optional[StrictInt] = Field(default=None, description="Number of times topology changed.", alias="topChanges")
    designated_root: Optional[StrictStr] = Field(default=None, description="Bridge identifier of the root bridge", alias="designatedRoot")
    root_cost: Optional[StrictInt] = Field(default=None, description="Value of the Root Path Cost for the common and internal spanning tree", alias="rootCost")
    root_port: Optional[StrictInt] = Field(default=None, description="Root port identifier", alias="rootPort")
    max_age: Optional[StrictInt] = Field(default=None, description="Maximum age", alias="maxAge")
    hello_time: Optional[StrictInt] = Field(default=None, description="Hello time", alias="helloTime")
    hold_time: Optional[StrictInt] = Field(default=None, description="Hold time", alias="holdTime")
    forward_delay: Optional[StrictInt] = Field(default=None, description="Forward delay", alias="forwardDelay")
    bridge_max_age: Optional[StrictInt] = Field(default=None, description="Bridge maximum age", alias="bridgeMaxAge")
    bridge_hello_time: Optional[StrictInt] = Field(default=None, description="Bridge hello time", alias="bridgeHelloTime")
    bridge_forward_delay: Optional[StrictInt] = Field(default=None, description="Bridge forward delay", alias="bridgeForwardDelay")
    __properties: ClassVar[List[str]] = ["protocolSpecification", "priority", "timeSinceTopologyChange", "topChanges", "designatedRoot", "rootCost", "rootPort", "maxAge", "helloTime", "holdTime", "forwardDelay", "bridgeMaxAge", "bridgeHelloTime", "bridgeForwardDelay"]

    @field_validator('protocol_specification')
    def protocol_specification_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['dot1d', 'unknown']):
            raise ValueError("must be one of enum values ('dot1d', 'unknown')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Dot1dStpConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Dot1dStpConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "protocolSpecification": obj.get("protocolSpecification"),
            "priority": obj.get("priority"),
            "timeSinceTopologyChange": obj.get("timeSinceTopologyChange"),
            "topChanges": obj.get("topChanges"),
            "designatedRoot": obj.get("designatedRoot"),
            "rootCost": obj.get("rootCost"),
            "rootPort": obj.get("rootPort"),
            "maxAge": obj.get("maxAge"),
            "helloTime": obj.get("helloTime"),
            "holdTime": obj.get("holdTime"),
            "forwardDelay": obj.get("forwardDelay"),
            "bridgeMaxAge": obj.get("bridgeMaxAge"),
            "bridgeHelloTime": obj.get("bridgeHelloTime"),
            "bridgeForwardDelay": obj.get("bridgeForwardDelay")
        })
        return _obj


