# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.sw_portstats_neighbor_info import SwPortstatsNeighborInfo
from typing import Optional, Set
from typing_extensions import Self

class SwPortstats(BaseModel):
    """
    SwPortstats
    """ # noqa: E501
    port_id: Optional[StrictInt] = Field(default=None, description="Port Number", alias="portId")
    switch_name: Optional[StrictStr] = Field(default=None, description="Name of Switch", alias="switchName")
    my_desc: Optional[StrictStr] = Field(default=None, description="Port description", alias="myDesc")
    admin_mode: Optional[StrictBool] = Field(default=None, description="Admin Mode of port", alias="adminMode")
    status: Optional[StrictInt] = Field(default=None, description="Link Status:   * `0` = LINK_UP   * `1` = LINK_DOWN ")
    poe_status: Optional[StrictInt] = Field(default=None, description="PoE Status:   * `-1` = STATUS_INVALID   * `0` = STATUS_DISABLED   * `1` = STATUS_SEARCHING   * `2` = STATUS_DELIVERING_POWER   * `3` = STATUS_TEST   * `4` = STATUS_FAULT   * `5` = STATUS_OTHER_FAULT   * `6` = STATUS_REQUESTING_POWER   * `7` = STATUS_OVERLOAD ", alias="poeStatus")
    mode: Optional[StrictInt] = Field(default=None, description="Port Mode:   * `0` = MODE_NONE   * `1` = MODE_GENERAL   * `2` = MODE_ACCESS   * `3` = MODE_TRUNK   * `4` = MODE_PRIVATE_HOST   * `5` = MODE_PRIVATE_PROMISC ")
    vlans: Optional[List[StrictInt]] = None
    traffic_rx: Optional[StrictInt] = Field(default=None, description="Total number of bytes received", alias="trafficRx")
    traffic_tx: Optional[StrictInt] = Field(default=None, description="Total number of bytes transmitted", alias="trafficTx")
    rx_mbps: Optional[StrictStr] = Field(default=None, description="Current receive bit rate in Mbps", alias="rxMbps")
    tx_mbps: Optional[StrictStr] = Field(default=None, description="Current transmit bit rate in Mbps", alias="txMbps")
    crc_errors_rx: Optional[StrictInt] = Field(default=None, description="Total numver of packets with CRC errors received", alias="crcErrorsRx")
    errors_rx_tx: Optional[StrictInt] = Field(default=None, description="Number of error packets", alias="errorsRxTx")
    drops_rx_tx: Optional[StrictInt] = Field(default=None, description="Number of packets dropped", alias="dropsRxTx")
    port_mac_address: Optional[StrictStr] = Field(default=None, description="Port MAC Address", alias="portMacAddress")
    speed: Optional[StrictInt] = Field(default=None, description="Interface Speed:   * `1` = SPEED_AUTO_NEG   * `2` = SPEED_HALF_100TX   * `3` = SPEED_FULL_100TX   * `4` = SPEED_HALF_10T   * `5` = SPEED_FULL_10T   * `6` = SPEED_FULL_100FX   * `7` = SPEED_FULL_1000SX   * `8` = SPEED_FULL_10GSX   * `9` = SPEED_FULL_20GSX   * `10` = SPEED_FULL_40GSX   * `11` = SPEED_FULL_25GSX   * `12` = SPEED_FULL_50GSX   * `13` = SPEED_FULL_100GSX   * `14` = SPEED_AAL5_155   * `15` = SPEED_FULL_5FX   * `128` = SPEED_FULL_2P5FX   * `129` = SPEED_LAG   * `130` = SPEED_UNKNOWN ")
    duplex: Optional[StrictInt] = Field(default=None, description="Interface Duplex mode:   * `0` = half   * `1` = full   * `65535` = auto ")
    frame_size: Optional[StrictInt] = Field(default=None, description="Packets size measured in Maximum Transmission Units", alias="frameSize")
    flow_control: Optional[StrictBool] = Field(default=None, description="Flow control enabled", alias="flowControl")
    lacp_mode: Optional[StrictBool] = Field(default=None, description="LACP enabled", alias="lacpMode")
    mirrored: Optional[StrictBool] = Field(default=None, description="Port mirror enabled")
    stp_status: Optional[StrictBool] = Field(default=None, description="STP admin mode enabled on the port", alias="stpStatus")
    port_state: Optional[StrictInt] = Field(default=None, description="STP port state:   * `1` = Discarding   * `2` = Learning   * `3` = Forwarding   * `4` = Disabled   * `5` = Manual forwarding   * `6` = Not participate ", alias="portState")
    opr_state: Optional[StrictInt] = Field(default=None, description="Port operational state:   * `0` = DIAG_PORT_DISABLE   * `1` = DIAG_PORT_ENABLE   * `2` DIAG_PORT_D_DISABLE ", alias="oprState")
    power_limit_class: Optional[StrictInt] = Field(default=None, description="PoE port power class:   * `0` = INVALID   * `1` = CLASS0   * `2` = CLASS1   * `3` = CLASS2   * `4` = CLASS3   * `5` = CLASS4 ", alias="powerLimitClass")
    neighbor_info: Optional[SwPortstatsNeighborInfo] = Field(default=None, alias="neighborInfo")
    port_auth_state: Optional[StrictInt] = Field(default=None, description="Port authorization state:   * `1` = Authorised   * `2` = Unauthorised   * `3` = N/A ", alias="portAuthState")
    __properties: ClassVar[List[str]] = ["portId", "switchName", "myDesc", "adminMode", "status", "poeStatus", "mode", "vlans", "trafficRx", "trafficTx", "rxMbps", "txMbps", "crcErrorsRx", "errorsRxTx", "dropsRxTx", "portMacAddress", "speed", "duplex", "frameSize", "flowControl", "lacpMode", "mirrored", "stpStatus", "portState", "oprState", "powerLimitClass", "neighborInfo", "portAuthState"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('poe_status')
    def poe_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([-1, 0, 1, 2, 3, 4, 5, 6, 7]):
            raise ValueError("must be one of enum values (-1, 0, 1, 2, 3, 4, 5, 6, 7)")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2, 3, 4, 5]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4, 5)")
        return value

    @field_validator('speed')
    def speed_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 128, 129, 130]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 128, 129, 130)")
        return value

    @field_validator('duplex')
    def duplex_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 65535]):
            raise ValueError("must be one of enum values (0, 1, 65535)")
        return value

    @field_validator('port_state')
    def port_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 5, 6]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 5, 6)")
        return value

    @field_validator('opr_state')
    def opr_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2]):
            raise ValueError("must be one of enum values (0, 1, 2)")
        return value

    @field_validator('power_limit_class')
    def power_limit_class_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2, 3, 4, 5]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4, 5)")
        return value

    @field_validator('port_auth_state')
    def port_auth_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3]):
            raise ValueError("must be one of enum values (1, 2, 3)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwPortstats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of neighbor_info
        if self.neighbor_info:
            _dict['neighborInfo'] = self.neighbor_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwPortstats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "portId": obj.get("portId"),
            "switchName": obj.get("switchName"),
            "myDesc": obj.get("myDesc"),
            "adminMode": obj.get("adminMode"),
            "status": obj.get("status"),
            "poeStatus": obj.get("poeStatus"),
            "mode": obj.get("mode"),
            "vlans": obj.get("vlans"),
            "trafficRx": obj.get("trafficRx"),
            "trafficTx": obj.get("trafficTx"),
            "rxMbps": obj.get("rxMbps"),
            "txMbps": obj.get("txMbps"),
            "crcErrorsRx": obj.get("crcErrorsRx"),
            "errorsRxTx": obj.get("errorsRxTx"),
            "dropsRxTx": obj.get("dropsRxTx"),
            "portMacAddress": obj.get("portMacAddress"),
            "speed": obj.get("speed"),
            "duplex": obj.get("duplex"),
            "frameSize": obj.get("frameSize"),
            "flowControl": obj.get("flowControl"),
            "lacpMode": obj.get("lacpMode"),
            "mirrored": obj.get("mirrored"),
            "stpStatus": obj.get("stpStatus"),
            "portState": obj.get("portState"),
            "oprState": obj.get("oprState"),
            "powerLimitClass": obj.get("powerLimitClass"),
            "neighborInfo": SwPortstatsNeighborInfo.from_dict(obj["neighborInfo"]) if obj.get("neighborInfo") is not None else None,
            "portAuthState": obj.get("portAuthState")
        })
        return _obj


