/var/log/cms/*.log {
    daily
    rotate 30
    missingok
    notifempty
    compress
    delaycompress
    create 644 root root
    postrotate
        reload rsyslog >/dev/null 2>&1 || true
    endscript
}
