# flake8: noqa

# import apis into api package
from openapi_client.api.authentication_api import AuthenticationApi
from openapi_client.api.device_settings_api import DeviceSettingsApi
from openapi_client.api.diagnostics_api import DiagnosticsApi
from openapi_client.api.link_aggregration_group_settings_api import LinkAggregrationGroupSettingsApi
from openapi_client.api.logging_api import LoggingApi
from openapi_client.api.multicast_api import MulticastApi
from openapi_client.api.port_information_and_settings_api import PortInformationAndSettingsApi
from openapi_client.api.power_over_ethernet_information_and_settings_api import PowerOverEthernetInformationAndSettingsApi
from openapi_client.api.quality_of_service_api import QualityOfServiceApi
from openapi_client.api.routing_settings_api import RoutingSettingsApi
from openapi_client.api.spanning_tree_protocol_api import SpanningTreeProtocolApi
from openapi_client.api.virtual_local_area_networks_api import VirtualLocalAreaNetworksApi

