# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.snooping_queriers_post_request import (
    SnoopingQueriersPostRequest,
)


class TestSnoopingQueriersPostRequest(unittest.TestCase):
    """SnoopingQueriersPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnoopingQueriersPostRequest:
        """Test SnoopingQueriersPostRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SnoopingQueriersPostRequest`
        """
        model = SnoopingQueriersPostRequest()
        if include_optional:
            return SnoopingQueriersPostRequest(
                snooping_queriers = {"address":"0.0.0.0","adminMode":"enabled","expiryInterval":126,"queryInterval":63,"querierVersion":1,"vlanAddress":"192.168.55.22","vlanElectionMode":"enabled"}
            )
        else:
            return SnoopingQueriersPostRequest(
        )
        """

    def testSnoopingQueriersPostRequest(self):
        """Test SnoopingQueriersPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
