# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1d_base_config import Dot1dBaseConfig

class TestDot1dBaseConfig(unittest.TestCase):
    """Dot1dBaseConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1dBaseConfig:
        """Test Dot1dBaseConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1dBaseConfig`
        """
        model = Dot1dBaseConfig()
        if include_optional:
            return Dot1dBaseConfig(
                base_bridge_address = '8C:3B:AD:66:C6:98',
                base_num_ports = 78,
                base_type = 2
            )
        else:
            return Dot1dBaseConfig(
        )
        """

    def testDot1dBaseConfig(self):
        """Test Dot1dBaseConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
