# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.device_settings_api import DeviceSettingsApi


class TestDeviceSettingsApi(unittest.TestCase):
    """DeviceSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_active_image_get(self) -> None:
        """Test case for active_image_get

        """
        pass

    def test_active_image_post(self) -> None:
        """Test case for active_image_post

        """
        pass

    def test_bonjour_get(self) -> None:
        """Test case for bonjour_get

        """
        pass

    def test_bonjour_post(self) -> None:
        """Test case for bonjour_post

        """
        pass

    def test_config_copy_post(self) -> None:
        """Test case for config_copy_post

        """
        pass

    def test_config_file_compare_get(self) -> None:
        """Test case for config_file_compare_get

        """
        pass

    def test_device_info_get(self) -> None:
        """Test case for device_info_get

        """
        pass

    def test_device_name_get(self) -> None:
        """Test case for device_name_get

        """
        pass

    def test_device_name_post(self) -> None:
        """Test case for device_name_post

        """
        pass

    def test_device_reboot_post(self) -> None:
        """Test case for device_reboot_post

        """
        pass

    def test_dual_image_status_get(self) -> None:
        """Test case for dual_image_status_get

        """
        pass

    def test_lldp_remote_devices_get(self) -> None:
        """Test case for lldp_remote_devices_get

        """
        pass

    def test_system_config_get(self) -> None:
        """Test case for system_config_get

        """
        pass

    def test_system_config_post(self) -> None:
        """Test case for system_config_post

        """
        pass

    def test_system_rfc1213_get(self) -> None:
        """Test case for system_rfc1213_get

        """
        pass

    def test_system_rfc1213_post(self) -> None:
        """Test case for system_rfc1213_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
