# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_port_get200_response import SwcfgPortGet200Response


class TestSwcfgPortGet200Response(unittest.TestCase):
    """SwcfgPortGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwcfgPortGet200Response:
        """Test SwcfgPortGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SwcfgPortGet200Response`
        """
        model = SwcfgPortGet200Response()
        if include_optional:
            return SwcfgPortGet200Response(
                switch_port_config = {"ID":0,"description":"ntgr_port_g15","portType":1,"adminMode":true,"portSpeed":0,"duplexMode":2,"linkStatus":0,"linkTrap":true,"maxFrameSize":1518,"isPoE":true,"txRate":0,"rtlimitUcast":{"status":true,"threshold":10},"rtlimitMcast":{"status":true,"threshold":10},"rtlimitBcast":{"status":true,"threshold":10},"portVlanId":1,"defVlanPrio":0,"scheduleName":"Schedule_1"}
            )
        else:
            return SwcfgPortGet200Response(
        )
        """

    def testSwcfgPortGet200Response(self):
        """Test SwcfgPortGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
