# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1d_stp_config import Dot1dStpConfig

class TestDot1dStpConfig(unittest.TestCase):
    """Dot1dStpConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1dStpConfig:
        """Test Dot1dStpConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1dStpConfig`
        """
        model = Dot1dStpConfig()
        if include_optional:
            return Dot1dStpConfig(
                protocol_specification = 'dot1d',
                priority = 0,
                time_since_topology_change = 56,
                top_changes = 56,
                designated_root = '',
                root_cost = 56,
                root_port = 56,
                max_age = 56,
                hello_time = 56,
                hold_time = 56,
                forward_delay = 56,
                bridge_max_age = 56,
                bridge_hello_time = 56,
                bridge_forward_delay = 56
            )
        else:
            return Dot1dStpConfig(
        )
        """

    def testDot1dStpConfig(self):
        """Test Dot1dStpConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
