# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sw_portmirroring_get200_response import (
    SwPortmirroringGet200Response,
)


class TestSwPortmirroringGet200Response(unittest.TestCase):
    """SwPortmirroringGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwPortmirroringGet200Response:
        """Test SwPortmirroringGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SwPortmirroringGet200Response`
        """
        model = SwPortmirroringGet200Response()
        if include_optional:
            return SwPortmirroringGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                switch_rstp_port_config = {"sessionNum":1,"sessionMode":false,"destPort":10,"srcPort":[{"intfType":0,"intfNum":24,"direction":1},{"intfType":1,"intfNum":313,"direction":1},{"intfType":2,"intfNum":320,"direction":1}]}
            )
        else:
            return SwPortmirroringGet200Response(
        )
        """

    def testSwPortmirroringGet200Response(self):
        """Test SwPortmirroringGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
