# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.snooping_vlan_get200_response import (
    SnoopingVlanGet200Response,
)


class TestSnoopingVlanGet200Response(unittest.TestCase):
    """SnoopingVlanGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnoopingVlanGet200Response:
        """Test SnoopingVlanGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SnoopingVlanGet200Response`
        """
        model = SnoopingVlanGet200Response()
        if include_optional:
            return SnoopingVlanGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success',
                    resp_code = 0,
                    resp_msg = 'Operation success', ),
                snooping_vlans = [{"vlanId":1,"family":"igmp","fastLeaveMode":"enabled","vlanMode":"disabled","reportSuppMode":"disabled","proxyQuerierMode":"enabled","groupMembershipInterval":260,"maxResponseTime":10}]
            )
        else:
            return SnoopingVlanGet200Response(
        )
        """

    def testSnoopingVlanGet200Response(self):
        """Test SnoopingVlanGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
