# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dual_image_status import DualImageStatus

class TestDualImageStatus(unittest.TestCase):
    """DualImageStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DualImageStatus:
        """Test DualImageStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DualImageStatus`
        """
        model = DualImageStatus()
        if include_optional:
            return DualImageStatus(
                image1_label = 'image1',
                image1_descr = '',
                image1_version = '',
                image2_label = 'image2',
                image2_descr = '',
                image2_version = '',
                activated_img_label = ''
            )
        else:
            return DualImageStatus(
        )
        """

    def testDualImageStatus(self):
        """Test DualImageStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
