# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.link_aggregration_group_settings_api import (
    LinkAggregrationGroupSettingsApi,
)


class TestLinkAggregrationGroupSettingsApi(unittest.TestCase):
    """LinkAggregrationGroupSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinkAggregrationGroupSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_sw_lag_cfg_get(self) -> None:
        """Test case for sw_lag_cfg_get"""
        pass

    def test_sw_lag_cfg_post(self) -> None:
        """Test case for sw_lag_cfg_post"""
        pass


if __name__ == "__main__":
    unittest.main()
