# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sw_portmirroring_src_port_inner import SwPortmirroringSrcPortInner

class TestSwPortmirroringSrcPortInner(unittest.TestCase):
    """SwPortmirroringSrcPortInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwPortmirroringSrcPortInner:
        """Test SwPortmirroringSrcPortInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwPortmirroringSrcPortInner`
        """
        model = SwPortmirroringSrcPortInner()
        if include_optional:
            return SwPortmirroringSrcPortInner(
                intf_type = 0,
                intf_num = 56,
                direction = 1
            )
        else:
            return SwPortmirroringSrcPortInner(
                intf_type = 0,
                intf_num = 56,
                direction = 1,
        )
        """

    def testSwPortmirroringSrcPortInner(self):
        """Test SwPortmirroringSrcPortInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
