# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.host_table_get200_response import HostTableGet200Response


class TestHostTableGet200Response(unittest.TestCase):
    """HostTableGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostTableGet200Response:
        """Test HostTableGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HostTableGet200Response`
        """
        model = HostTableGet200Response()
        if include_optional:
            return HostTableGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                host_table = [
                    openapi_client.models.host_table.host_table(
                        ip_addr = '10.120.166.108', 
                        mac_addr = 'B0:39:56:8D:2D:E4', 
                        vlan_id = 3, )
                    ]
            )
        else:
            return HostTableGet200Response(
        )
        """

    def testHostTableGet200Response(self):
        """Test HostTableGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
