# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ping_test_status_get200_response import (
    PingTestStatusGet200Response,
)


class TestPingTestStatusGet200Response(unittest.TestCase):
    """PingTestStatusGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PingTestStatusGet200Response:
        """Test PingTestStatusGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PingTestStatusGet200Response`
        """
        model = PingTestStatusGet200Response()
        if include_optional:
            return PingTestStatusGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                ping_test_status = openapi_client.models.ping_test_status.ping_test_status(
                    state = 0, 
                    ping_msg = '....', )
            )
        else:
            return PingTestStatusGet200Response(
        )
        """

    def testPingTestStatusGet200Response(self):
        """Test PingTestStatusGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
