# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_vlan_get200_response import SwcfgVlanGet200Response

class TestSwcfgVlanGet200Response(unittest.TestCase):
    """SwcfgVlanGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwcfgVlanGet200Response:
        """Test SwcfgVlanGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwcfgVlanGet200Response`
        """
        model = SwcfgVlanGet200Response()
        if include_optional:
            return SwcfgVlanGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                switch_config_vlan = {"vlanId":1,"name":"Management VLAN","voiceVlanState":true,"autoVoipState":false,"autoVideoState":false,"igmpConfig":{"igmpState":false}}
            )
        else:
            return SwcfgVlanGet200Response(
        )
        """

    def testSwcfgVlanGet200Response(self):
        """Test SwcfgVlanGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
