# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fdb_stats_get200_response import FdbStatsGet200Response

class TestFdbStatsGet200Response(unittest.TestCase):
    """FdbStatsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FdbStatsGet200Response:
        """Test FdbStatsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FdbStatsGet200Response`
        """
        model = FdbStatsGet200Response()
        if include_optional:
            return FdbStatsGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                fdb_stats = {"staticEntries":2,"dynamicEntries":110,"maxTableEntries":16384,"currentTableEntries":112,"greatestTableEntries":133}
            )
        else:
            return FdbStatsGet200Response(
        )
        """

    def testFdbStatsGet200Response(self):
        """Test FdbStatsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
