# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.traceroute_status_get200_response import TracerouteStatusGet200Response

class TestTracerouteStatusGet200Response(unittest.TestCase):
    """TracerouteStatusGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TracerouteStatusGet200Response:
        """Test TracerouteStatusGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TracerouteStatusGet200Response`
        """
        model = TracerouteStatusGet200Response()
        if include_optional:
            return TracerouteStatusGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                traceroute_info = openapi_client.models.traceroute_status.traceroute_status(
                    state = 0, 
                    traceroute_msg = '....', )
            )
        else:
            return TracerouteStatusGet200Response(
        )
        """

    def testTracerouteStatusGet200Response(self):
        """Test TracerouteStatusGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
