# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.poe_config_post_request import PoeConfigPostRequest

class TestPoeConfigPostRequest(unittest.TestCase):
    """PoeConfigPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoeConfigPostRequest:
        """Test PoeConfigPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoeConfigPostRequest`
        """
        model = PoeConfigPostRequest()
        if include_optional:
            return PoeConfigPostRequest(
                poe_config = {"pseMainOperationStatus":"enabled","usageThreshold":95,"powerManagmentMode":"static","powerDetectionMode":3,"traps":"enabled"}
            )
        else:
            return PoeConfigPostRequest(
        )
        """

    def testPoeConfigPostRequest(self):
        """Test PoeConfigPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
