# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.device_cable_test_get200_response import (
    DeviceCableTestGet200Response,
)


class TestDeviceCableTestGet200Response(unittest.TestCase):
    """DeviceCableTestGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceCableTestGet200Response:
        """Test DeviceCableTestGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeviceCableTestGet200Response`
        """
        model = DeviceCableTestGet200Response()
        if include_optional:
            return DeviceCableTestGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success',
                    resp_code = 0,
                    resp_msg = 'Operation success', ),
                cable_test_status = {"status":2,"lenKnown":1,"shortestLen":0,"longestLen":12,"cableFailureLen":0}
            )
        else:
            return DeviceCableTestGet200Response(
        )
        """

    def testDeviceCableTestGet200Response(self):
        """Test DeviceCableTestGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
