# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1d_stp_entries_get200_response import Dot1dStpEntriesGet200Response

class TestDot1dStpEntriesGet200Response(unittest.TestCase):
    """Dot1dStpEntriesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1dStpEntriesGet200Response:
        """Test Dot1dStpEntriesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1dStpEntriesGet200Response`
        """
        model = Dot1dStpEntriesGet200Response()
        if include_optional:
            return Dot1dStpEntriesGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                dot1d_stp_entries = [{"port":1,"priority":32768,"state":"enabled","pathCost":1,"designatedRoot":"80:00:8C:3B:AD:66:C6:98","designatedCost":0,"designatedBridge":"80:00:8C:3B:AD:66:C6:98","designatedPort":4800},{"port":52,"priority":32768,"state":"enabled","pathCost":1,"designatedRoot":"80:00:8C:3B:AD:66:C6:98","designatedCost":0,"designatedBridge":"80:00:8C:3B:AD:66:C6:98","designatedPort":"00:0"}]
            )
        else:
            return Dot1dStpEntriesGet200Response(
        )
        """

    def testDot1dStpEntriesGet200Response(self):
        """Test Dot1dStpEntriesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
