# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fdb_stats_get import FdbStatsGet


class TestFdbStatsGet(unittest.TestCase):
    """FdbStatsGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FdbStatsGet:
        """Test FdbStatsGet
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FdbStatsGet`
        """
        model = FdbStatsGet()
        if include_optional:
            return FdbStatsGet(
                static_entries = 56,
                dynamic_entries = 56,
                max_table_entries = 56,
                current_table_entries = 56,
                greatest_table_entries = 56
            )
        else:
            return FdbStatsGet(
        )
        """

    def testFdbStatsGet(self):
        """Test FdbStatsGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
