# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.poe_config_get200_response import PoeConfigGet200Response


class TestPoeConfigGet200Response(unittest.TestCase):
    """PoeConfigGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoeConfigGet200Response:
        """Test PoeConfigGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PoeConfigGet200Response`
        """
        model = PoeConfigGet200Response()
        if include_optional:
            return PoeConfigGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                poe_config = {"firmwareVersion":"11.6.10.6","pseMainOperationStatus":false,"totalPowerConsumedWatts":0.0,"powerManagmentMode":"Static","traps":"enable","powerDetectionMode":3}
            )
        else:
            return PoeConfigGet200Response(
        )
        """

    def testPoeConfigGet200Response(self):
        """Test PoeConfigGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
