# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.costrust_get200_response import CostrustGet200Response

class TestCostrustGet200Response(unittest.TestCase):
    """CostrustGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CostrustGet200Response:
        """Test CostrustGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CostrustGet200Response`
        """
        model = CostrustGet200Response()
        if include_optional:
            return CostrustGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                costrust = openapi_client.models.costrust.costrust(
                    mode = 'ip-dscp', )
            )
        else:
            return CostrustGet200Response(
        )
        """

    def testCostrustGet200Response(self):
        """Test CostrustGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
