# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.system_rfc1213_get200_response import SystemRfc1213Get200Response

class TestSystemRfc1213Get200Response(unittest.TestCase):
    """SystemRfc1213Get200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemRfc1213Get200Response:
        """Test SystemRfc1213Get200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemRfc1213Get200Response`
        """
        model = SystemRfc1213Get200Response()
        if include_optional:
            return SystemRfc1213Get200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                system_rfc1213 = {"sysDescr":"M4300-24X ProSAFE 20-port 10GBASE-T and 4-port 10G combo, 20.36.53.1, B1.0.0.15","sysName":"M4324X","sysLocation":"San Jose","sysContact":""}
            )
        else:
            return SystemRfc1213Get200Response(
        )
        """

    def testSystemRfc1213Get200Response(self):
        """Test SystemRfc1213Get200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
