# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.download_status import DownloadStatus

class TestDownloadStatus(unittest.TestCase):
    """DownloadStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DownloadStatus:
        """Test DownloadStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DownloadStatus`
        """
        model = DownloadStatus()
        if include_optional:
            return DownloadStatus(
                state = 0,
                message = 'Download Status None',
                dwld_progress = ''
            )
        else:
            return DownloadStatus(
        )
        """

    def testDownloadStatus(self):
        """Test DownloadStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
