# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ping_test_status import PingTestStatus

class TestPingTestStatus(unittest.TestCase):
    """PingTestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PingTestStatus:
        """Test PingTestStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PingTestStatus`
        """
        model = PingTestStatus()
        if include_optional:
            return PingTestStatus(
                state = 0,
                ping_msg = '....'
            )
        else:
            return PingTestStatus(
        )
        """

    def testPingTestStatus(self):
        """Test PingTestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
