# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.quality_of_service_api import QualityOfServiceApi


class TestQualityOfServiceApi(unittest.TestCase):
    """QualityOfServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QualityOfServiceApi()

    def tearDown(self) -> None:
        pass

    def test_cos_queue_config_get(self) -> None:
        """Test case for cos_queue_config_get

        """
        pass

    def test_cos_queue_config_post(self) -> None:
        """Test case for cos_queue_config_post

        """
        pass

    def test_costrust_get(self) -> None:
        """Test case for costrust_get

        """
        pass

    def test_costrust_post(self) -> None:
        """Test case for costrust_post

        """
        pass

    def test_dot1p_queue_map_get(self) -> None:
        """Test case for dot1p_queue_map_get

        """
        pass

    def test_dot1p_queue_map_post(self) -> None:
        """Test case for dot1p_queue_map_post

        """
        pass

    def test_ipdscp_queue_map_get(self) -> None:
        """Test case for ipdscp_queue_map_get

        """
        pass

    def test_ipdscp_queue_map_post(self) -> None:
        """Test case for ipdscp_queue_map_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
