# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1d_stp_entries_inner import Dot1dStpEntriesInner


class TestDot1dStpEntriesInner(unittest.TestCase):
    """Dot1dStpEntriesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1dStpEntriesInner:
        """Test Dot1dStpEntriesInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Dot1dStpEntriesInner`
        """
        model = Dot1dStpEntriesInner()
        if include_optional:
            return Dot1dStpEntriesInner(
                port = 56,
                priority = 56,
                state = '',
                path_cost = 56,
                designated_root = '',
                designated_cost = 56,
                designated_bridge = '',
                designated_port = ''
            )
        else:
            return Dot1dStpEntriesInner(
        )
        """

    def testDot1dStpEntriesInner(self):
        """Test Dot1dStpEntriesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
