# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1s_interfaces_post_request import Dot1sInterfacesPostRequest

class TestDot1sInterfacesPostRequest(unittest.TestCase):
    """Dot1sInterfacesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1sInterfacesPostRequest:
        """Test Dot1sInterfacesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1sInterfacesPostRequest`
        """
        model = Dot1sInterfacesPostRequest()
        if include_optional:
            return Dot1sInterfacesPostRequest(
                dot1s_interfaces = {"bpduFilterMode":true,"bpduFloodMode":true,"intfEdgePortMode":true,"intfGuardMode":2,"intfMode":true}
            )
        else:
            return Dot1sInterfacesPostRequest(
        )
        """

    def testDot1sInterfacesPostRequest(self):
        """Test Dot1sInterfacesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
