# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.snooping_interfaces_post import SnoopingInterfacesPost

class TestSnoopingInterfacesPost(unittest.TestCase):
    """SnoopingInterfacesPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnoopingInterfacesPost:
        """Test SnoopingInterfacesPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnoopingInterfacesPost`
        """
        model = SnoopingInterfacesPost()
        if include_optional:
            return SnoopingInterfacesPost(
                interface = 56,
                family = 'igmp',
                fast_leave_admin_mode = '',
                group_membership_interval = 56,
                intf_mode = '',
                proxy_querier_mode = '',
                response_time = 56
            )
        else:
            return SnoopingInterfacesPost(
                interface = 56,
                family = 'igmp',
                fast_leave_admin_mode = '',
                group_membership_interval = 56,
                intf_mode = '',
                proxy_querier_mode = '',
                response_time = 56,
        )
        """

    def testSnoopingInterfacesPost(self):
        """Test SnoopingInterfacesPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
