# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.msti_get200_response import MstiGet200Response


class TestMstiGet200Response(unittest.TestCase):
    """MstiGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MstiGet200Response:
        """Test MstiGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MstiGet200Response`
        """
        model = MstiGet200Response()
        if include_optional:
            return MstiGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                dot1s_msti_entries = [{"mstId":0,"priority":0,"vlans":[{"id":1,"type":"Default","name":"Default"},{"id":201,"type":"Static","name":"FacultyNetwork"},{"id":202,"type":"Static","name":"GuestNetwork"}]},{"mstId":12,"priority":32768,"vlans":[{"id":4089,"type":"Auto-Video","name":"Auto-Video"}]}]
            )
        else:
            return MstiGet200Response(
        )
        """

    def testMstiGet200Response(self):
        """Test MstiGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
