# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ip_route_table import IpRouteTable


class TestIpRouteTable(unittest.TestCase):
    """IpRouteTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IpRouteTable:
        """Test IpRouteTable
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IpRouteTable`
        """
        model = IpRouteTable()
        if include_optional:
            return IpRouteTable(
                next_hop_intf = '',
                route_mask = '',
                next_hop_addr = '',
                route_type = '',
                route_proto = '',
                route_dest = '',
                metric = 56,
                route_pref = 1
            )
        else:
            return IpRouteTable(
        )
        """

    def testIpRouteTable(self):
        """Test IpRouteTable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
