# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ping_test_start_post_request import PingTestStartPostRequest

class TestPingTestStartPostRequest(unittest.TestCase):
    """PingTestStartPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PingTestStartPostRequest:
        """Test PingTestStartPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PingTestStartPostRequest`
        """
        model = PingTestStartPostRequest()
        if include_optional:
            return PingTestStartPostRequest(
                ping_test = {"action":1,"ipVersion":4,"host":"1.1.1.1","count":3,"size":64,"timeout":60,"interval":1}
            )
        else:
            return PingTestStartPostRequest(
        )
        """

    def testPingTestStartPostRequest(self):
        """Test PingTestStartPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
