# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.msti_post_request import MstiPostRequest

class TestMstiPostRequest(unittest.TestCase):
    """MstiPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MstiPostRequest:
        """Test MstiPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MstiPostRequest`
        """
        model = MstiPostRequest()
        if include_optional:
            return MstiPostRequest(
                dot1s_msti_entries = openapi_client.models.msti_post.msti_post(
                    vlanid = 1, 
                    priority = 128, )
            )
        else:
            return MstiPostRequest(
        )
        """

    def testMstiPostRequest(self):
        """Test MstiPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
