# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.poe_config_get import PoeConfigGet


class TestPoeConfigGet(unittest.TestCase):
    """PoeConfigGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoeConfigGet:
        """Test PoeConfigGet
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PoeConfigGet`
        """
        model = PoeConfigGet()
        if include_optional:
            return PoeConfigGet(
                firmware_version = '',
                pse_main_operation_status = 'true',
                total_power_consumed_watts = '',
                power_managment_mode = 'dynamic',
                traps = 'enable',
                power_detection_mode = 56
            )
        else:
            return PoeConfigGet(
        )
        """

    def testPoeConfigGet(self):
        """Test PoeConfigGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
