# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vlan_ip_configuration import VlanIpConfiguration


class TestVlanIpConfiguration(unittest.TestCase):
    """VlanIpConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VlanIpConfiguration:
        """Test VlanIpConfiguration
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VlanIpConfiguration`
        """
        model = VlanIpConfiguration()
        if include_optional:
            return VlanIpConfiguration(
                dhcp_status = True,
                vlan_id = 56,
                ip_mtu = 68
            )
        else:
            return VlanIpConfiguration(
                dhcp_status = True,
                vlan_id = 56,
                ip_mtu = 68,
        )
        """

    def testVlanIpConfiguration(self):
        """Test VlanIpConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
