# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.system_rfc1213_post_request import SystemRfc1213PostRequest

class TestSystemRfc1213PostRequest(unittest.TestCase):
    """SystemRfc1213PostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemRfc1213PostRequest:
        """Test SystemRfc1213PostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemRfc1213PostRequest`
        """
        model = SystemRfc1213PostRequest()
        if include_optional:
            return SystemRfc1213PostRequest(
                system_rfc1213 = {"sysName":"M4324X","sysLocation":"San Jose","sysContact":""}
            )
        else:
            return SystemRfc1213PostRequest(
        )
        """

    def testSystemRfc1213PostRequest(self):
        """Test SystemRfc1213PostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
