# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.multicast_api import MulticastApi


class TestMulticastApi(unittest.TestCase):
    """MulticastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MulticastApi()

    def tearDown(self) -> None:
        pass

    def test_snooping_config_get(self) -> None:
        """Test case for snooping_config_get

        """
        pass

    def test_snooping_config_post(self) -> None:
        """Test case for snooping_config_post

        """
        pass

    def test_snooping_interfaces_get(self) -> None:
        """Test case for snooping_interfaces_get

        """
        pass

    def test_snooping_interfaces_post(self) -> None:
        """Test case for snooping_interfaces_post

        """
        pass

    def test_snooping_queriers_get(self) -> None:
        """Test case for snooping_queriers_get

        """
        pass

    def test_snooping_queriers_post(self) -> None:
        """Test case for snooping_queriers_post

        """
        pass

    def test_snooping_vlan_get(self) -> None:
        """Test case for snooping_vlan_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
