# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ptpv2_post_request import Ptpv2PostRequest

class TestPtpv2PostRequest(unittest.TestCase):
    """Ptpv2PostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ptpv2PostRequest:
        """Test Ptpv2PostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ptpv2PostRequest`
        """
        model = Ptpv2PostRequest()
        if include_optional:
            return Ptpv2PostRequest(
                ptpv2 = openapi_client.models.ptpv2_post.ptpv2_post(
                    admin_mode = 'enabled', )
            )
        else:
            return Ptpv2PostRequest(
        )
        """

    def testPtpv2PostRequest(self):
        """Test Ptpv2PostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
