# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_poe_post_request import SwcfgPoePostRequest

class TestSwcfgPoePostRequest(unittest.TestCase):
    """SwcfgPoePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwcfgPoePostRequest:
        """Test SwcfgPoePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwcfgPoePostRequest`
        """
        model = SwcfgPoePostRequest()
        if include_optional:
            return SwcfgPoePostRequest(
                poe_port_config = {"enable":true,"powerLimitMode":1,"classification":1,"currentPower":30000,"powerLimit":30000,"status":2,"reset":false}
            )
        else:
            return SwcfgPoePostRequest(
        )
        """

    def testSwcfgPoePostRequest(self):
        """Test SwcfgPoePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
