# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.msti_get_inner import MstiGetInner

class TestMstiGetInner(unittest.TestCase):
    """MstiGetInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MstiGetInner:
        """Test MstiGetInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MstiGetInner`
        """
        model = MstiGetInner()
        if include_optional:
            return MstiGetInner(
                mst_id = 56,
                priority = 56,
                vlans = [
                    openapi_client.models.msti_get_inner_vlans_inner.msti_get_inner_vlans_inner(
                        id = 56, 
                        type = '', 
                        name = '', )
                    ]
            )
        else:
            return MstiGetInner(
        )
        """

    def testMstiGetInner(self):
        """Test MstiGetInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
