# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ptpv2_get import Ptpv2Get


class TestPtpv2Get(unittest.TestCase):
    """Ptpv2Get unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ptpv2Get:
        """Test Ptpv2Get
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Ptpv2Get`
        """
        model = Ptpv2Get()
        if include_optional:
            return Ptpv2Get(
                admin_mode = 'enabled',
                opera_mode = 'enabled'
            )
        else:
            return Ptpv2Get(
                admin_mode = 'enabled',
                opera_mode = 'enabled',
        )
        """

    def testPtpv2Get(self):
        """Test Ptpv2Get"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
