# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.device_info_get200_response import DeviceInfoGet200Response


class TestDeviceInfoGet200Response(unittest.TestCase):
    """DeviceInfoGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceInfoGet200Response:
        """Test DeviceInfoGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeviceInfoGet200Response`
        """
        model = DeviceInfoGet200Response()
        if include_optional:
            return DeviceInfoGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success',
                    resp_code = 0,
                    resp_msg = 'Operation success', ),
                device_info = {"name":"","serialNumber":"N1MN648000T","macAddr":"10:DA:43:D7:72:F9","model":"GC110P","lanIpAddress":"10.120.166.73","swVer":"1.27.12.48","lastReboot":"hu, 09 Mar 2017 06:08:21 (UTC+05:30 IST)","numOfPorts":10,"numOfActivePorts":1,"rstpState":false,"memoryUsed":"153968 KB","memoryUsage":"64.45%","cpuUsage":"6.40%","fanState":"active","poeState":true,"upTime":"00 Days 03 Hrs 32 Mins 08 Secs","temperatureSensors":{"sensorNum":1,"sensorDesc":"MAC","sensorTemp":68,"sensorState":1},"bootVersion":"1.0.0.1","rxData":1796615,"txData":3802563,"adminPoePower":120000}
            )
        else:
            return DeviceInfoGet200Response(
        )
        """

    def testDeviceInfoGet200Response(self):
        """Test DeviceInfoGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
