# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_vlan_membership_traffic_prio_lag_mem_inner import (
    SwcfgVlanMembershipTrafficPrioLagMemInner,
)


class TestSwcfgVlanMembershipTrafficPrioLagMemInner(unittest.TestCase):
    """SwcfgVlanMembershipTrafficPrioLagMemInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> SwcfgVlanMembershipTrafficPrioLagMemInner:
        """Test SwcfgVlanMembershipTrafficPrioLagMemInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SwcfgVlanMembershipTrafficPrioLagMemInner`
        """
        model = SwcfgVlanMembershipTrafficPrioLagMemInner()
        if include_optional:
            return SwcfgVlanMembershipTrafficPrioLagMemInner(
                portid = 56
            )
        else:
            return SwcfgVlanMembershipTrafficPrioLagMemInner(
        )
        """

    def testSwcfgVlanMembershipTrafficPrioLagMemInner(self):
        """Test SwcfgVlanMembershipTrafficPrioLagMemInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
