# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.download import Download


class TestDownload(unittest.TestCase):
    """Download unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Download:
        """Test Download
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Download`
        """
        model = Download()
        if include_optional:
            return Download(
                protocol = 'tftp',
                fw_url = '',
                fw_download_timeout = 56,
                reboot_now = True,
                type = 'backup-config',
                image = 1
            )
        else:
            return Download(
                protocol = 'tftp',
                fw_url = '',
                fw_download_timeout = 56,
                reboot_now = True,
                type = 'backup-config',
                image = 1,
        )
        """

    def testDownload(self):
        """Test Download"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
