# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.traceroute_start import TracerouteStart


class TestTracerouteStart(unittest.TestCase):
    """TracerouteStart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TracerouteStart:
        """Test TracerouteStart
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TracerouteStart`
        """
        model = TracerouteStart()
        if include_optional:
            return TracerouteStart(
                action = 1,
                host = 'www.netgear.com',
                size = 38,
                ip_version = 4,
                init_ttl = 1,
                max_ttl = 1,
                port = 1,
                n_queries = 1,
                wait = 1
            )
        else:
            return TracerouteStart(
                action = 1,
                host = 'www.netgear.com',
        )
        """

    def testTracerouteStart(self):
        """Test TracerouteStart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
