# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_port_rtlimit_mcast import SwcfgPortRtlimitMcast


class TestSwcfgPortRtlimitMcast(unittest.TestCase):
    """SwcfgPortRtlimitMcast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwcfgPortRtlimitMcast:
        """Test SwcfgPortRtlimitMcast
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SwcfgPortRtlimitMcast`
        """
        model = SwcfgPortRtlimitMcast()
        if include_optional:
            return SwcfgPortRtlimitMcast(
                status = True,
                threshold = 56
            )
        else:
            return SwcfgPortRtlimitMcast(
                status = True,
                threshold = 56,
        )
        """

    def testSwcfgPortRtlimitMcast(self):
        """Test SwcfgPortRtlimitMcast"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
