# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.port_information_and_settings_api import (
    PortInformationAndSettingsApi,
)


class TestPortInformationAndSettingsApi(unittest.TestCase):
    """PortInformationAndSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortInformationAndSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_device_reset_counters_post(self) -> None:
        """Test case for device_reset_counters_post"""
        pass

    def test_dot1d_base_config_get(self) -> None:
        """Test case for dot1d_base_config_get"""
        pass

    def test_dot1d_tp_config_get(self) -> None:
        """Test case for dot1d_tp_config_get"""
        pass

    def test_dot1d_tp_config_post(self) -> None:
        """Test case for dot1d_tp_config_post"""
        pass

    def test_dot1d_tp_port_entries_get(self) -> None:
        """Test case for dot1d_tp_port_entries_get"""
        pass

    def test_fdb_stats_get(self) -> None:
        """Test case for fdb_stats_get"""
        pass

    def test_fdb_stats_post(self) -> None:
        """Test case for fdb_stats_post"""
        pass

    def test_fdbs_delete(self) -> None:
        """Test case for fdbs_delete"""
        pass

    def test_fdbs_get(self) -> None:
        """Test case for fdbs_get"""
        pass

    def test_fiber_optics_get(self) -> None:
        """Test case for fiber_optics_get"""
        pass

    def test_ptpv2_get(self) -> None:
        """Test case for ptpv2_get"""
        pass

    def test_ptpv2_global_get(self) -> None:
        """Test case for ptpv2_global_get"""
        pass

    def test_ptpv2_global_post(self) -> None:
        """Test case for ptpv2_global_post"""
        pass

    def test_ptpv2_post(self) -> None:
        """Test case for ptpv2_post"""
        pass

    def test_sw_portstats_get(self) -> None:
        """Test case for sw_portstats_get"""
        pass

    def test_swcfg_port_get(self) -> None:
        """Test case for swcfg_port_get"""
        pass

    def test_swcfg_port_post(self) -> None:
        """Test case for swcfg_port_post"""
        pass


if __name__ == "__main__":
    unittest.main()
