# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fdbs_get200_response import FdbsGet200Response


class TestFdbsGet200Response(unittest.TestCase):
    """FdbsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FdbsGet200Response:
        """Test FdbsGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FdbsGet200Response`
        """
        model = FdbsGet200Response()
        if include_optional:
            return FdbsGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success',
                    resp_code = 0,
                    resp_msg = 'Operation success', ),
                fdb_stats = [{"interface":1,"vlanId":1,"mac":"00:17:61:11:0D:4E","entryType":1},{"interface":1,"vlanId":1,"mac":"00:17:61:11:AF:E8","entryType":1},{"interface":1,"vlanId":1,"mac":"00:26:6C:1E:78:EB","entryType":1}]
            )
        else:
            return FdbsGet200Response(
        )
        """

    def testFdbsGet200Response(self):
        """Test FdbsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
