# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1q_sw_port_config_post import Dot1qSwPortConfigPost


class TestDot1qSwPortConfigPost(unittest.TestCase):
    """Dot1qSwPortConfigPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1qSwPortConfigPost:
        """Test Dot1qSwPortConfigPost
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Dot1qSwPortConfigPost`
        """
        model = Dot1qSwPortConfigPost()
        if include_optional:
            return Dot1qSwPortConfigPost(
                access_vlan = 56,
                allowed_vlan_list = [
                    ''
                    ],
                config_mode = 'none',
                native_vlan = ''
            )
        else:
            return Dot1qSwPortConfigPost(
                access_vlan = 56,
                allowed_vlan_list = [
                    ''
                    ],
                config_mode = 'none',
                native_vlan = '',
        )
        """

    def testDot1qSwPortConfigPost(self):
        """Test Dot1qSwPortConfigPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
