# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1p_queue_map_post_request import Dot1pQueueMapPostRequest

class TestDot1pQueueMapPostRequest(unittest.TestCase):
    """Dot1pQueueMapPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1pQueueMapPostRequest:
        """Test Dot1pQueueMapPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1pQueueMapPostRequest`
        """
        model = Dot1pQueueMapPostRequest()
        if include_optional:
            return Dot1pQueueMapPostRequest(
                dot1p_queue_map = [{"priority":0,"queuemap":0},{"priority":1,"queuemap":1},{"priority":2,"queuemap":0},{"priority":3,"queuemap":1},{"priority":4,"queuemap":0},{"priority":5,"queuemap":2},{"priority":6,"queuemap":2},{"priority":7,"queuemap":3}]
            )
        else:
            return Dot1pQueueMapPostRequest(
        )
        """

    def testDot1pQueueMapPostRequest(self):
        """Test Dot1pQueueMapPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
