# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.lldp_remote_devices_get200_response import LldpRemoteDevicesGet200Response

class TestLldpRemoteDevicesGet200Response(unittest.TestCase):
    """LldpRemoteDevicesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LldpRemoteDevicesGet200Response:
        """Test LldpRemoteDevicesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LldpRemoteDevicesGet200Response`
        """
        model = LldpRemoteDevicesGet200Response()
        if include_optional:
            return LldpRemoteDevicesGet200Response(
                lldp_remote_devices = {"id":31,"ifIndex":31,"remoteId":5,"chassisId":"A0:40:A0:5B:41:AF","chassisIdSubtype":4,"remotePortId":"A0:40:A0:5B:41:AF","remotePortIdSubtype":3,"remotePortDesc":"lldp0","remoteSysName":"BioTech-Wing","remoteSysDesc":"Linux 3.14.77 #3 SMP PREEMPT Fri Jun 19 09:44:29 GMT 2020 armv7l","sysCapabilitiesSupported":["bridge, WLAN access point"],"sysCapabilitiesEnabled":["bridge, WLAN access point"],"mgmtAddresses":{"type":"IPv4","address":"192.168.8.58"},"remoteTTL":18}
            )
        else:
            return LldpRemoteDevicesGet200Response(
        )
        """

    def testLldpRemoteDevicesGet200Response(self):
        """Test LldpRemoteDevicesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
