# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.stp_get200_response import StpGet200Response


class TestStpGet200Response(unittest.TestCase):
    """StpGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StpGet200Response:
        """Test StpGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `StpGet200Response`
        """
        model = StpGet200Response()
        if include_optional:
            return StpGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                spanning_tree = {"status":true,"rootBridgePriority":32768,"stpMode":0,"rootBridgeId":"","ports":[1,2,3],"lagGroupID":[1,2,3]}
            )
        else:
            return StpGet200Response(
        )
        """

    def testStpGet200Response(self):
        """Test StpGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
