# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_poe import SwcfgPoe

class TestSwcfgPoe(unittest.TestCase):
    """SwcfgPoe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwcfgPoe:
        """Test SwcfgPoe
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwcfgPoe`
        """
        model = SwcfgPoe()
        if include_optional:
            return SwcfgPoe(
                portid = 56,
                enable = True,
                power_limit_mode = 0,
                classification = 0,
                current_power = 0,
                power_limit = 0,
                status = -1,
                reset = True
            )
        else:
            return SwcfgPoe(
                enable = True,
                power_limit_mode = 0,
                classification = 0,
                power_limit = 0,
        )
        """

    def testSwcfgPoe(self):
        """Test SwcfgPoe"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
