# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1d_tp_config_post_request import Dot1dTpConfigPostRequest


class TestDot1dTpConfigPostRequest(unittest.TestCase):
    """Dot1dTpConfigPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1dTpConfigPostRequest:
        """Test Dot1dTpConfigPostRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Dot1dTpConfigPostRequest`
        """
        model = Dot1dTpConfigPostRequest()
        if include_optional:
            return Dot1dTpConfigPostRequest(
                dot1d_tp_config = openapi_client.models.dot1d_tp_config_post.dot1d_tp_config_post(
                    aging_time = 300, )
            )
        else:
            return Dot1dTpConfigPostRequest(
        )
        """

    def testDot1dTpConfigPostRequest(self):
        """Test Dot1dTpConfigPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
