# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.system_rfc1213_get import SystemRfc1213Get


class TestSystemRfc1213Get(unittest.TestCase):
    """SystemRfc1213Get unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemRfc1213Get:
        """Test SystemRfc1213Get
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SystemRfc1213Get`
        """
        model = SystemRfc1213Get()
        if include_optional:
            return SystemRfc1213Get(
                sys_descr = '',
                sys_name = '',
                sys_location = '',
                sys_contact = ''
            )
        else:
            return SystemRfc1213Get(
        )
        """

    def testSystemRfc1213Get(self):
        """Test SystemRfc1213Get"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
