# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ptpv2_global_get200_response import Ptpv2GlobalGet200Response


class TestPtpv2GlobalGet200Response(unittest.TestCase):
    """Ptpv2GlobalGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ptpv2GlobalGet200Response:
        """Test Ptpv2GlobalGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Ptpv2GlobalGet200Response`
        """
        model = Ptpv2GlobalGet200Response()
        if include_optional:
            return Ptpv2GlobalGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success',
                    resp_code = 0,
                    resp_msg = 'Operation success', ),
                ptpv2_global = openapi_client.models.ptpv2_global.ptpv2_global(
                    admin_mode = 'enabled', )
            )
        else:
            return Ptpv2GlobalGet200Response(
        )
        """

    def testPtpv2GlobalGet200Response(self):
        """Test Ptpv2GlobalGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
