# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.device_info import DeviceInfo


class TestDeviceInfo(unittest.TestCase):
    """DeviceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceInfo:
        """Test DeviceInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeviceInfo`
        """
        model = DeviceInfo()
        if include_optional:
            return DeviceInfo(
                name = '',
                serial_number = '',
                mac_addr = '',
                model = '',
                lan_ip_address = '',
                sw_ver = '',
                last_reboot = '',
                num_of_ports = 56,
                num_of_active_ports = 56,
                rstp_state = True,
                memory_used = '',
                memory_usage = '',
                cpu_usage = '',
                fan_state = '',
                poe_state = True,
                up_time = '',
                temperature_sensors = [
                    openapi_client.models.device_info_temperature_sensors_inner.device_info_temperatureSensors_inner(
                        sensor_num = 56,
                        sensor_desc = 56,
                        sensor_temp = '',
                        sensor_state = '0', )
                    ],
                boot_version = '',
                rx_data = 56,
                tx_data = 56,
                admin_poe_power = 56
            )
        else:
            return DeviceInfo(
        )
        """

    def testDeviceInfo(self):
        """Test DeviceInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
