# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dual_image_status_get200_response import DualImageStatusGet200Response

class TestDualImageStatusGet200Response(unittest.TestCase):
    """DualImageStatusGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DualImageStatusGet200Response:
        """Test DualImageStatusGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DualImageStatusGet200Response`
        """
        model = DualImageStatusGet200Response()
        if include_optional:
            return DualImageStatusGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                dual_image_status = {"image1Label":"image1","image1Descr":"","image1Version":"3.28.0.1","image2Label":"image2","image2Descr":"","image2Version":"3.30.11.1","activatedImgLabel":"image2"}
            )
        else:
            return DualImageStatusGet200Response(
        )
        """

    def testDualImageStatusGet200Response(self):
        """Test DualImageStatusGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
