# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1q_sw_port_config_post_request import (
    Dot1qSwPortConfigPostRequest,
)


class TestDot1qSwPortConfigPostRequest(unittest.TestCase):
    """Dot1qSwPortConfigPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1qSwPortConfigPostRequest:
        """Test Dot1qSwPortConfigPostRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Dot1qSwPortConfigPostRequest`
        """
        model = Dot1qSwPortConfigPostRequest()
        if include_optional:
            return Dot1qSwPortConfigPostRequest(
                dot1q_sw_port_config = {"accessVlan":1,"allowedVlanList":["all"],"configMode":"access","nativeVlan":1}
            )
        else:
            return Dot1qSwPortConfigPostRequest(
        )
        """

    def testDot1qSwPortConfigPostRequest(self):
        """Test Dot1qSwPortConfigPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
