# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auto_voip_cfg_get import AutoVoipCfgGet


class TestAutoVoipCfgGet(unittest.TestCase):
    """AutoVoipCfgGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoVoipCfgGet:
        """Test AutoVoipCfgGet
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AutoVoipCfgGet`
        """
        model = AutoVoipCfgGet()
        if include_optional:
            return AutoVoipCfgGet(
                vlan_id = 56,
                supported_channels = 56,
                used_channels = 56,
                protocol_based = openapi_client.models.auto_voip_cfg_get_protocol_based.auto_voip_cfg_get_protocolBased(
                    prioritization_type = 'traffic-class', 
                    class_value = 0, 
                    mode = True, 
                    status = True, ),
                oui_based = openapi_client.models.auto_voip_cfg_get_oui_based.auto_voip_cfg_get_ouiBased(
                    priority = 0, 
                    mode = True, 
                    status = True, )
            )
        else:
            return AutoVoipCfgGet(
        )
        """

    def testAutoVoipCfgGet(self):
        """Test AutoVoipCfgGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
