# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bonjour_get200_response import BonjourGet200Response

class TestBonjourGet200Response(unittest.TestCase):
    """BonjourGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BonjourGet200Response:
        """Test BonjourGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BonjourGet200Response`
        """
        model = BonjourGet200Response()
        if include_optional:
            return BonjourGet200Response(
                bonjour = openapi_client.models.bonjour.bonjour(
                    status = 'enabled', )
            )
        else:
            return BonjourGet200Response(
        )
        """

    def testBonjourGet200Response(self):
        """Test BonjourGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
