# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1p_queue_map_get200_response import Dot1pQueueMapGet200Response

class TestDot1pQueueMapGet200Response(unittest.TestCase):
    """Dot1pQueueMapGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1pQueueMapGet200Response:
        """Test Dot1pQueueMapGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1pQueueMapGet200Response`
        """
        model = Dot1pQueueMapGet200Response()
        if include_optional:
            return Dot1pQueueMapGet200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success', 
                    resp_code = 0, 
                    resp_msg = 'Operation success', ),
                dot1p_queue_map = [{"priority":0,"queuemap":0},{"priority":1,"queuemap":1},{"priority":2,"queuemap":0},{"priority":3,"queuemap":1},{"priority":4,"queuemap":0},{"priority":5,"queuemap":2},{"priority":6,"queuemap":2},{"priority":7,"queuemap":3}]
            )
        else:
            return Dot1pQueueMapGet200Response(
        )
        """

    def testDot1pQueueMapGet200Response(self):
        """Test Dot1pQueueMapGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
