# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.swcfg_vlan_post_request import SwcfgVlanPostRequest

class TestSwcfgVlanPostRequest(unittest.TestCase):
    """SwcfgVlanPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwcfgVlanPostRequest:
        """Test SwcfgVlanPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwcfgVlanPostRequest`
        """
        model = SwcfgVlanPostRequest()
        if include_optional:
            return SwcfgVlanPostRequest(
                switch_config_vlan = {"vlanId":1,"name":"Management VLAN","voiceVlanState":true,"autoVoipState":false,"autoVideoState":false,"igmpConfig":{"igmpState":false}}
            )
        else:
            return SwcfgVlanPostRequest(
        )
        """

    def testSwcfgVlanPostRequest(self):
        """Test SwcfgVlanPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
