# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.power_over_ethernet_information_and_settings_api import (
    PowerOverEthernetInformationAndSettingsApi,
)


class TestPowerOverEthernetInformationAndSettingsApi(unittest.TestCase):
    """PowerOverEthernetInformationAndSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PowerOverEthernetInformationAndSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_poe_config_get(self) -> None:
        """Test case for poe_config_get"""
        pass

    def test_poe_config_post(self) -> None:
        """Test case for poe_config_post"""
        pass

    def test_swcfg_poe_get(self) -> None:
        """Test case for swcfg_poe_get"""
        pass

    def test_swcfg_poe_post(self) -> None:
        """Test case for swcfg_poe_post"""
        pass


if __name__ == "__main__":
    unittest.main()
