# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ptpv2_get200_response import Ptpv2Get200Response


class TestPtpv2Get200Response(unittest.TestCase):
    """Ptpv2Get200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ptpv2Get200Response:
        """Test Ptpv2Get200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Ptpv2Get200Response`
        """
        model = Ptpv2Get200Response()
        if include_optional:
            return Ptpv2Get200Response(
                resp = openapi_client.models.general_responses_code.general_responses_code(
                    status = 'success',
                    resp_code = 0,
                    resp_msg = 'Operation success', ),
                ptpv2 = openapi_client.models.ptpv2_get.ptpv2_get(
                    admin_mode = 'enabled',
                    opera_mode = 'enabled', )
            )
        else:
            return Ptpv2Get200Response(
        )
        """

    def testPtpv2Get200Response(self):
        """Test Ptpv2Get200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
