# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dot1s_interfaces_post import Dot1sInterfacesPost

class TestDot1sInterfacesPost(unittest.TestCase):
    """Dot1sInterfacesPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dot1sInterfacesPost:
        """Test Dot1sInterfacesPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dot1sInterfacesPost`
        """
        model = Dot1sInterfacesPost()
        if include_optional:
            return Dot1sInterfacesPost(
                interface = 56,
                bpdu_filter_mode = True,
                bpdu_flood_mode = True,
                intf_edge_port_mode = True,
                intf_guard_mode = 0,
                intf_mode = True
            )
        else:
            return Dot1sInterfacesPost(
        )
        """

    def testDot1sInterfacesPost(self):
        """Test Dot1sInterfacesPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
