# coding: utf-8

"""
M4300 REST API

M4300 REST API with ConfigAgent Documentation.

The version of the OpenAPI document: 2.0.0.59
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.snooping_config_post import SnoopingConfigPost


class TestSnoopingConfigPost(unittest.TestCase):
    """SnoopingConfigPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnoopingConfigPost:
        """Test SnoopingConfigPost
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SnoopingConfigPost`
        """
        model = SnoopingConfigPost()
        if include_optional:
            return SnoopingConfigPost(
                family = 'mdl',
                admin_mode = 'enabled',
                proxy_querier_admin_mode = 'enabled',
                flood_all_unknown_port = 'enabled'
            )
        else:
            return SnoopingConfigPost(
                family = 'mdl',
                admin_mode = 'enabled',
                proxy_querier_admin_mode = 'enabled',
                flood_all_unknown_port = 'enabled',
        )
        """

    def testSnoopingConfigPost(self):
        """Test SnoopingConfigPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
