# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.voice_vlan_cfg import VoiceVlanCfg

class TestVoiceVlanCfg(unittest.TestCase):
    """VoiceVlanCfg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceVlanCfg:
        """Test VoiceVlanCfg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceVlanCfg`
        """
        model = VoiceVlanCfg()
        if include_optional:
            return VoiceVlanCfg(
                mode = 1,
                value = 3
            )
        else:
            return VoiceVlanCfg(
                mode = 1,
                value = 3,
        )
        """

    def testVoiceVlanCfg(self):
        """Test VoiceVlanCfg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
