# coding: utf-8

"""
    M4300 REST API

    M4300 REST API with ConfigAgent Documentation.

    The version of the OpenAPI document: 2.0.0.59
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.device_reboot_post_request import DeviceRebootPostRequest

class TestDeviceRebootPostRequest(unittest.TestCase):
    """DeviceRebootPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceRebootPostRequest:
        """Test DeviceRebootPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceRebootPostRequest`
        """
        model = DeviceRebootPostRequest()
        if include_optional:
            return DeviceRebootPostRequest(
                device_reboot = openapi_client.models.device_reboot.device_reboot(
                    after_secs = 10, )
            )
        else:
            return DeviceRebootPostRequest(
        )
        """

    def testDeviceRebootPostRequest(self):
        """Test DeviceRebootPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
