# Generated by Django 5.1.4 on 2025-01-13 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name - must be unique",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category if this is a subcategory",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="File name with extension", max_length=255
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Relative path to file in storage", max_length=1024
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FIRMWARE", "Firmware"),
                            ("DOC", "Documentation"),
                            ("CONFIG", "Configuration"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of file content",
                        max_length=10,
                    ),
                ),
                ("size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum of file content", max_length=64
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags associated with the file",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="cms.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="FileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("path", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="cms_filetag_name_647e62_idx"),
                    models.Index(fields=["path"], name="cms_filetag_path_afa216_idx"),
                ],
                "unique_together": {("name", "path")},
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Version identifier", max_length=50),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum of this version", max_length=64
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True, help_text="Description of changes in this version"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cms.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-upload_date"],
                "unique_together": {("file", "version")},
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="Metadata key name", max_length=255),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Metadata value - supports JSON structure"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="cms.file",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "metadata",
                "ordering": ["key"],
                "unique_together": {("file", "key")},
            },
        ),
    ]
