# Generated by Django 5.1.5 on 2025-01-30 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        protocol="IPv4",
                        validators=[django.core.validators.validate_ipv4_address],
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "switches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("version", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="switches.switch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "admin_status",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down")],
                        default="up",
                        max_length=4,
                    ),
                ),
                (
                    "vlan",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4094),
                        ]
                    ),
                ),
                (
                    "speed",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("1G", "1 Gbps"),
                            ("10G", "10 Gbps"),
                            ("40G", "40 Gbps"),
                        ],
                        default="auto",
                        max_length=4,
                    ),
                ),
                (
                    "duplex",
                    models.CharField(
                        choices=[("auto", "Auto"), ("full", "Full"), ("half", "Half")],
                        default="auto",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="switches.switch",
                    ),
                ),
            ],
            options={
                "ordering": ["switch", "name"],
                "unique_together": {("switch", "name")},
            },
        ),
    ]
