# Generated by Django 5.1.5 on 2025-02-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="switch",
            name="status",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("down", "Down"),
                    ("degraded", "Degraded"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
