# Generated by Django 5.1.5 on 2025-02-03 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0002_switch_last_seen_switch_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="switch",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="switch",
            name="in_band_ip",
            field=models.GenericIPAddressField(
                default="169.254.0.0",
                help_text="In-band management IP address",
                protocol="IPv4",
                validators=[django.core.validators.validate_ipv4_address],
                verbose_name="In-Band IP",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="switch",
            name="out_band_ip",
            field=models.GenericIPAddressField(
                default="192.168.0.239",
                help_text="Out-of-band management IP address",
                protocol="IPv4",
                validators=[django.core.validators.validate_ipv4_address],
                verbose_name="Out-Band IP",
            ),
            preserve_default=False,
        ),
    ]
