# Generated by Django 5.1.5 on 2025-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0003_remove_switch_ip_address_switch_in_band_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="auth_status",
            field=models.CharField(
                choices=[
                    ("authenticated", "Authenticated"),
                    ("unauthenticated", "Unauthenticated"),
                    ("error", "Error"),
                ],
                default="unauthenticated",
                help_text="Current authentication status with the switch",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="auth_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="switch",
            name="token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
