# Generated by Django 5.1.5 on 2025-02-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0004_switch_auth_status_switch_auth_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="switch",
            name="last_seen",
        ),
        migrations.AddField(
            model_name="switch",
            name="in_band_last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Last successful connection to in-band interface",
                null=True,
                verbose_name="In-Band Last Seen",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="in_band_status",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("down", "Down"),
                    ("degraded", "Degraded"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Status of the in-band management interface",
                max_length=20,
                verbose_name="In-Band Status",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="out_band_last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Last successful connection to out-band interface",
                null=True,
                verbose_name="Out-Band Last Seen",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="out_band_status",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("down", "Down"),
                    ("degraded", "Degraded"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Status of the out-of-band management interface",
                max_length=20,
                verbose_name="Out-Band Status",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="status_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed status information and history",
            ),
        ),
        migrations.AlterField(
            model_name="switch",
            name="status",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("down", "Down"),
                    ("degraded", "Degraded"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Aggregate status based on both interfaces",
                max_length=20,
            ),
        ),
    ]
