# Generated by Django 5.1.5 on 2025-02-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0005_remove_switch_last_seen_switch_in_band_last_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="in_band_error",
            field=models.CharField(
                choices=[
                    ("auth_failed", "Authentication failed"),
                    ("ssl_error", "SSL certificate error"),
                    ("no_response", "No response from switch"),
                    ("api_error", "API error"),
                    ("none", "No error"),
                ],
                default="none",
                help_text="Last error encountered on in-band interface",
                max_length=20,
                verbose_name="In-Band Error",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="in_band_error_detail",
            field=models.CharField(
                blank=True,
                help_text="Detailed error message for in-band interface",
                max_length=255,
                verbose_name="In-Band Error Detail",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="in_band_response_time",
            field=models.FloatField(
                blank=True,
                help_text="Last response time in milliseconds",
                null=True,
                verbose_name="In-Band Response Time",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="out_band_error",
            field=models.CharField(
                choices=[
                    ("auth_failed", "Authentication failed"),
                    ("ssl_error", "SSL certificate error"),
                    ("no_response", "No response from switch"),
                    ("api_error", "API error"),
                    ("none", "No error"),
                ],
                default="none",
                help_text="Last error encountered on out-band interface",
                max_length=20,
                verbose_name="Out-Band Error",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="out_band_error_detail",
            field=models.CharField(
                blank=True,
                help_text="Detailed error message for out-band interface",
                max_length=255,
                verbose_name="Out-Band Error Detail",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="out_band_response_time",
            field=models.FloatField(
                blank=True,
                help_text="Last response time in milliseconds",
                null=True,
                verbose_name="Out-Band Response Time",
            ),
        ),
    ]
