# Generated by Django 4.2.20 on 2025-04-08 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version Number')),
                ('content', models.TextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changelog', models.TextField(blank=True, verbose_name='Change Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cms.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_document_files', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='cms.document', verbose_name='Document')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_documents', to='cms.file', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ['order', 'added_at'],
                'unique_together': {('document', 'file')},
            },
        ),
    ]
