# Generated by Django 3.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_documentversion_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_format',
            field=models.CharField(
                choices=[('html', 'HTML'), ('markdown', 'Markdown')],
                default='html',
                max_length=10,
                verbose_name='Content Format'
            ),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='content_format',
            field=models.CharField(
                choices=[('html', 'HTML'), ('markdown', 'Markdown')],
                default='html',
                max_length=10,
                verbose_name='Content Format'
            ),
        ),
    ]
