# Generated by Django 5.1.1 on 2024-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Netgear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=100)),
                ("in_band_ip", models.CharField(max_length=15)),
                ("out_band_ip", models.CharField(max_length=15)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("login_token", models.CharField(max_length=100)),
                ("login_epoch_time", models.IntegerField()),
            ],
        ),
    ]
