# Generated by Django 5.1.1 on 2024-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netgear",
            name="login_epoch_time",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="netgear",
            name="login_token",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
