# Generated by Django 5.1.3 on 2024-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the switch', max_length=100)),
                ('ip_address_in_band', models.GenericIPAddressField(help_text='IPv4 address for in-band management', protocol='IPv4')),
                ('ip_address_out_band', models.GenericIPAddressField(blank=True, help_text='IPv4 address for out-of-band management', null=True, protocol='IPv4')),
                ('mac_address', models.CharField(help_text='MAC address of the switch', max_length=17, unique=True)),
                ('model', models.CharField(help_text='Switch model number', max_length=100)),
                ('serial_number', models.CharField(help_text='Serial number of the switch', max_length=100, unique=True)),
                ('firmware_version', models.CharField(help_text='Current firmware version', max_length=50)),
                ('last_known_state', models.JSONField(blank=True, help_text='Last known state or configuration (JSON format)', null=True)),
                ('gold_master_config', models.JSONField(blank=True, help_text='Gold Master configuration (JSON format)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the switch', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Physical location or identifier', max_length=200, null=True)),
                ('port_count', models.PositiveIntegerField(help_text='Number of physical ports on the switch')),
                ('asset_id', models.CharField(blank=True, help_text='Inventory tracking asset ID', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional admin comments', null=True)),
                ('last_sync', models.DateTimeField(auto_now=True, help_text='Timestamp of the last synchronization')),
            ],
        ),
    ]
